<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-12-23">
<meta name="description" content="A worked Linear Programming example for the bank treasury function using SARB Basel III requirements (LCR, NSFR, CET1). Includes full LP formulation, step-by-step Simplex solution, shadow price interpretation, extensions to stochastic programming, and how the solver works mathematically.">

<title>Balance Sheet Optimisation Under South African Regulatory Constraints – Rossouw van Jaarsveld | Overfit and Chill</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7ab59434643fa729a91e673cdd1ca8e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Rossouw van Jaarsveld | Overfit and Chill</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/yourusername"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/yourprofile"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#mock-balance-sheet" id="toc-mock-balance-sheet" class="nav-link active" data-scroll-target="#mock-balance-sheet">1 — Mock Balance Sheet</a>
  <ul class="collapse">
  <li><a href="#assets" id="toc-assets" class="nav-link" data-scroll-target="#assets">Assets</a></li>
  <li><a href="#liabilities-capital-fixed" id="toc-liabilities-capital-fixed" class="nav-link" data-scroll-target="#liabilities-capital-fixed">Liabilities &amp; Capital (Fixed)</a></li>
  </ul></li>
  <li><a href="#south-african-regulatory-framework" id="toc-south-african-regulatory-framework" class="nav-link" data-scroll-target="#south-african-regulatory-framework">2 — South African Regulatory Framework</a>
  <ul class="collapse">
  <li><a href="#liquidity-coverage-ratio-lcr" id="toc-liquidity-coverage-ratio-lcr" class="nav-link" data-scroll-target="#liquidity-coverage-ratio-lcr">2.1 Liquidity Coverage Ratio (LCR)</a></li>
  <li><a href="#net-stable-funding-ratio-nsfr" id="toc-net-stable-funding-ratio-nsfr" class="nav-link" data-scroll-target="#net-stable-funding-ratio-nsfr">2.2 Net Stable Funding Ratio (NSFR)</a></li>
  <li><a href="#capital-adequacy-ratios" id="toc-capital-adequacy-ratios" class="nav-link" data-scroll-target="#capital-adequacy-ratios">2.3 Capital Adequacy Ratios</a></li>
  <li><a href="#leverage-ratio-cash-reserve-requirement" id="toc-leverage-ratio-cash-reserve-requirement" class="nav-link" data-scroll-target="#leverage-ratio-cash-reserve-requirement">2.4 Leverage Ratio &amp; Cash Reserve Requirement</a></li>
  </ul></li>
  <li><a href="#initial-balance-sheet-metrics" id="toc-initial-balance-sheet-metrics" class="nav-link" data-scroll-target="#initial-balance-sheet-metrics">3 — Initial Balance Sheet Metrics</a></li>
  <li><a href="#optimisation-problem-formulation" id="toc-optimisation-problem-formulation" class="nav-link" data-scroll-target="#optimisation-problem-formulation">4 — Optimisation Problem Formulation</a>
  <ul class="collapse">
  <li><a href="#decision-variables" id="toc-decision-variables" class="nav-link" data-scroll-target="#decision-variables">4.1 Decision Variables</a></li>
  <li><a href="#objective-function" id="toc-objective-function" class="nav-link" data-scroll-target="#objective-function">4.2 Objective Function</a></li>
  <li><a href="#constraints" id="toc-constraints" class="nav-link" data-scroll-target="#constraints">4.3 Constraints</a></li>
  <li><a href="#complete-lp-in-standard-form" id="toc-complete-lp-in-standard-form" class="nav-link" data-scroll-target="#complete-lp-in-standard-form">4.4 Complete LP in Standard Form</a></li>
  </ul></li>
  <li><a href="#step-by-step-solution" id="toc-step-by-step-solution" class="nav-link" data-scroll-target="#step-by-step-solution">5 — Step-by-Step Solution</a></li>
  <li><a href="#results-comparison" id="toc-results-comparison" class="nav-link" data-scroll-target="#results-comparison">6 — Results Comparison</a>
  <ul class="collapse">
  <li><a href="#balance-sheet-before-vs-after" id="toc-balance-sheet-before-vs-after" class="nav-link" data-scroll-target="#balance-sheet-before-vs-after">Balance Sheet Before vs After</a></li>
  <li><a href="#regulatory-metrics-before-vs-after" id="toc-regulatory-metrics-before-vs-after" class="nav-link" data-scroll-target="#regulatory-metrics-before-vs-after">Regulatory Metrics Before vs After</a></li>
  </ul></li>
  <li><a href="#extensions-dynamic-and-stochastic-optimisation" id="toc-extensions-dynamic-and-stochastic-optimisation" class="nav-link" data-scroll-target="#extensions-dynamic-and-stochastic-optimisation">7 — Extensions: Dynamic and Stochastic Optimisation</a>
  <ul class="collapse">
  <li><a href="#multi-period-lp-dynamic-programming" id="toc-multi-period-lp-dynamic-programming" class="nav-link" data-scroll-target="#multi-period-lp-dynamic-programming">7.1 Multi-Period LP (Dynamic Programming)</a></li>
  <li><a href="#stochastic-programming-with-scenario-trees" id="toc-stochastic-programming-with-scenario-trees" class="nav-link" data-scroll-target="#stochastic-programming-with-scenario-trees">7.2 Stochastic Programming with Scenario Trees</a></li>
  <li><a href="#quadratic-programme-risk-adjusted-return" id="toc-quadratic-programme-risk-adjusted-return" class="nav-link" data-scroll-target="#quadratic-programme-risk-adjusted-return">7.3 Quadratic Programme (Risk-Adjusted Return)</a></li>
  </ul></li>
  <li><a href="#economic-interpretation-shadow-prices" id="toc-economic-interpretation-shadow-prices" class="nav-link" data-scroll-target="#economic-interpretation-shadow-prices">8 — Economic Interpretation: Shadow Prices</a></li>
  <li><a href="#how-the-software-solves-the-lp" id="toc-how-the-software-solves-the-lp" class="nav-link" data-scroll-target="#how-the-software-solves-the-lp">9 — How the Software Solves the LP</a>
  <ul class="collapse">
  <li><a href="#standard-form-conversion" id="toc-standard-form-conversion" class="nav-link" data-scroll-target="#standard-form-conversion">9.1 Standard Form Conversion</a></li>
  <li><a href="#the-simplex-method" id="toc-the-simplex-method" class="nav-link" data-scroll-target="#the-simplex-method">9.2 The Simplex Method</a></li>
  <li><a href="#duality-and-the-dual-problem" id="toc-duality-and-the-dual-problem" class="nav-link" data-scroll-target="#duality-and-the-dual-problem">9.3 Duality and the Dual Problem</a></li>
  <li><a href="#interior-point-methods" id="toc-interior-point-methods" class="nav-link" data-scroll-target="#interior-point-methods">9.4 Interior Point Methods</a></li>
  <li><a href="#algorithm-comparison" id="toc-algorithm-comparison" class="nav-link" data-scroll-target="#algorithm-comparison">9.5 Algorithm Comparison</a></li>
  <li><a href="#julia-jump-implementation" id="toc-julia-jump-implementation" class="nav-link" data-scroll-target="#julia-jump-implementation">9.6 Julia / JuMP Implementation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Balance Sheet Optimisation Under South African Regulatory Constraints</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Finance</div>
    <div class="quarto-category">Optimisation</div>
    <div class="quarto-category">ALM</div>
    <div class="quarto-category">Banking</div>
  </div>
  </div>

<div>
  <div class="description">
    A worked Linear Programming example for the bank treasury function using SARB Basel III requirements (LCR, NSFR, CET1). Includes full LP formulation, step-by-step Simplex solution, shadow price interpretation, extensions to stochastic programming, and how the solver works mathematically.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>We construct a stylised mid-sized South African bank — <strong>No Gut Feelings Bank Ltd</strong> — and find the optimal allocation of its ZAR 330 bn productive asset base that maximises Net Interest Income (NII) subject to all SARB Basel III regulatory floors. The problem is formulated as a Linear Programme and solved in Julia using <code>JuMP.jl</code> and <code>HiGHS.jl</code>.</p>
<hr>
<section id="mock-balance-sheet" class="level2">
<h2 class="anchored" data-anchor-id="mock-balance-sheet">1 — Mock Balance Sheet</h2>
<p>The balance sheet has <strong>ZAR 350 bn</strong> in total assets. Liabilities and capital are held fixed; the seven asset classes below are the decision variables <span class="math inline">\(\mathbf{x} = (x_1, \ldots, x_7)\)</span>.</p>
<section id="assets" class="level3">
<h3 class="anchored" data-anchor-id="assets">Assets</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Asset Class</th>
<th>Var</th>
<th style="text-align: right;">Initial (ZAR bn)</th>
<th style="text-align: right;">Net Spread <span class="math inline">\(c_i\)</span></th>
<th style="text-align: right;">Risk Weight</th>
<th style="text-align: right;">RSF Factor</th>
<th>LCR HQLA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Liquidity Buffer</strong></td>
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td></td>
</tr>
<tr class="even">
<td>Cash &amp; SARB Reserves</td>
<td><span class="math inline">\(x_1\)</span></td>
<td style="text-align: right;">15.0</td>
<td style="text-align: right;">−0.50%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">0%</td>
<td>Level 1 — 100%</td>
</tr>
<tr class="odd">
<td>RSA Government Bonds</td>
<td><span class="math inline">\(x_2\)</span></td>
<td style="text-align: right;">25.0</td>
<td style="text-align: right;">+0.80%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">5%</td>
<td>Level 1 — 100%</td>
</tr>
<tr class="even">
<td>SOE / Parastatals Bonds</td>
<td><span class="math inline">\(x_3\)</span></td>
<td style="text-align: right;">15.0</td>
<td style="text-align: right;">+1.20%</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">15%</td>
<td>Level 2A — 85%</td>
</tr>
<tr class="odd">
<td><strong>Money Market</strong></td>
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td></td>
</tr>
<tr class="even">
<td>Interbank Loans (&lt; 30d)</td>
<td><span class="math inline">\(x_4\)</span></td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">+0.50%</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">15%</td>
<td>Inflow only</td>
</tr>
<tr class="odd">
<td><strong>Loan Book</strong></td>
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td></td>
</tr>
<tr class="even">
<td>Corporate Loans</td>
<td><span class="math inline">\(x_5\)</span></td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">+3.00%</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">50%</td>
<td>50% inflow</td>
</tr>
<tr class="odd">
<td>Retail Mortgages</td>
<td><span class="math inline">\(x_6\)</span></td>
<td style="text-align: right;">120.0</td>
<td style="text-align: right;">+2.50%</td>
<td style="text-align: right;">35%</td>
<td style="text-align: right;">65%</td>
<td>—</td>
</tr>
<tr class="even">
<td>Unsecured Retail Loans</td>
<td><span class="math inline">\(x_7\)</span></td>
<td style="text-align: right;">45.0</td>
<td style="text-align: right;">+6.00%</td>
<td style="text-align: right;">75%</td>
<td style="text-align: right;">85%</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Fixed Assets &amp; Other</td>
<td><span class="math inline">\(x_8\)</span></td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">100%</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Total Assets</strong></td>
<td></td>
<td style="text-align: right;"><strong>330.0</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spreads are annualised net margins above the blended cost of funds (approximately SARB repo rate + term premium). Cash earns below repo, creating a negative carry of −0.50%.</p>
</div>
</div>
</section>
<section id="liabilities-capital-fixed" class="level3">
<h3 class="anchored" data-anchor-id="liabilities-capital-fixed">Liabilities &amp; Capital (Fixed)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Liability / Capital Item</th>
<th style="text-align: right;">Balance (ZAR bn)</th>
<th style="text-align: right;">LCR Outflow Rate</th>
<th style="text-align: right;">ASF Factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Retail Deposits</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Retail Stable Deposits (insured / loyal)</td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">5%</td>
<td style="text-align: right;">95%</td>
</tr>
<tr class="odd">
<td>Retail Less Stable Deposits</td>
<td style="text-align: right;">70.0</td>
<td style="text-align: right;">10%</td>
<td style="text-align: right;">90%</td>
</tr>
<tr class="even">
<td><strong>Corporate Deposits</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Corporate Demand / Operational (&lt; 6 months)</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">25%</td>
<td style="text-align: right;">50%</td>
</tr>
<tr class="even">
<td>Corporate Term (&gt; 1 year)</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: right;">5%</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="odd">
<td><strong>Wholesale Funding</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Wholesale Funding (&lt; 6 months)</td>
<td style="text-align: right;">30.0</td>
<td style="text-align: right;">25%</td>
<td style="text-align: right;">50%</td>
</tr>
<tr class="odd">
<td>Wholesale Funding (&gt; 1 year)</td>
<td style="text-align: right;">30.0</td>
<td style="text-align: right;">5%</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="even">
<td>Interbank Borrowings (&lt; 30 days)</td>
<td style="text-align: right;">15.0</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">0%</td>
</tr>
<tr class="odd">
<td><strong>Capital</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Tier 2 Subordinated Debt</td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="odd">
<td>Additional Tier 1 (AT1)</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="even">
<td>Common Equity Tier 1 (CET1)</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="odd">
<td><strong>Total Liabilities &amp; Capital</strong></td>
<td style="text-align: right;"><strong>350.0</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="south-african-regulatory-framework" class="level2">
<h2 class="anchored" data-anchor-id="south-african-regulatory-framework">2 — South African Regulatory Framework</h2>
<p>The SARB implements Basel III through <strong>Regulation 38 of the Banks Act</strong> and associated circulars. Each ratio is translated into a linear constraint below.</p>
<section id="liquidity-coverage-ratio-lcr" class="level3">
<h3 class="anchored" data-anchor-id="liquidity-coverage-ratio-lcr">2.1 Liquidity Coverage Ratio (LCR)</h3>
<p>Effective from 1 January 2015, reaching its 100% minimum from 1 January 2019.</p>
<p><span class="math display">\[\text{LCR} = \frac{\text{HQLA}}{\text{Net Cash Outflows}_{30\text{-day stress}}} \;\geq\; 100\%\]</span></p>
<p><strong>HQLA composition:</strong></p>
<p><span class="math display">\[\text{HQLA} = \underbrace{x_1 + x_2}_{\text{Level 1 (no haircut)}} + \underbrace{0.85\, x_3}_{\text{Level 2A (15\% haircut)}}\]</span></p>
<p>The Level 2A composition cap (Level 2A <span class="math inline">\(\leq\)</span> 40% of HQLA) rearranges to:</p>
<p><span class="math display">\[0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \;\geq\; 0 \tag{L2A Cap}\]</span></p>
<p><strong>Net Cash Outflows (NCO):</strong></p>
<p><span class="math display">\[O = 80(0.05) + 70(0.10) + 50(0.25) + 40(0.05) + 30(0.25) + 30(0.05) + 15(1.00) = 49.50\]</span></p>
<p><span class="math display">\[\text{Inflow Cap} = 0.75 \times 49.50 = 37.125\]</span></p>
<p><span class="math display">\[\text{NCO} = O - \min(\text{Gross Inflows},\; 37.125) = 49.50 - 37.125 = 12.375\]</span></p>
<p>With <span class="math inline">\(x_5 = 80\)</span>, gross inflows from corporate loans alone (<span class="math inline">\(0.50 \times 80 = 40\)</span>) already exceed the 75% cap, so NCO is fixed at <strong>12.375</strong> regardless of the exact values of <span class="math inline">\(x_4\)</span> and <span class="math inline">\(x_5\)</span>.</p>
</section>
<section id="net-stable-funding-ratio-nsfr" class="level3">
<h3 class="anchored" data-anchor-id="net-stable-funding-ratio-nsfr">2.2 Net Stable Funding Ratio (NSFR)</h3>
<p>Required <span class="math inline">\(\geq\)</span> 100% in South Africa from 1 January 2018.</p>
<p><span class="math display">\[\text{NSFR} = \frac{\text{ASF}}{\text{RSF}} \;\geq\; 100\%\]</span></p>
<p><strong>ASF</strong> is fixed from the liability structure:</p>
<p><span class="math display">\[\text{ASF} = 20 + 5 + 10 + 80(0.95) + 70(0.90) + 40 + 30 + 30(0.50) + 50(0.50) + 15(0) = 284.00\]</span></p>
<p><strong>RSF</strong> depends on the asset decisions. Subtracting the fixed <span class="math inline">\(x_8\)</span> contribution of 20, the NSFR constraint <span class="math inline">\(\text{RSF} \leq 284\)</span> becomes:</p>
<p><span class="math display">\[0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \;\leq\; 264 \tag{NSFR}\]</span></p>
</section>
<section id="capital-adequacy-ratios" class="level3">
<h3 class="anchored" data-anchor-id="capital-adequacy-ratios">2.3 Capital Adequacy Ratios</h3>
<p>The minima <em>inclusive of the 2.5% Capital Conservation Buffer (CCB)</em> are:</p>
<p><span class="math display">\[\text{RWA} = 0.20\,x_3 + 0.20\,x_4 + 1.00\,x_5 + 0.35\,x_6 + 0.75\,x_7 + \underbrace{20}_{x_8,\;\text{fixed}}\]</span></p>
<p><span class="math display">\[\text{CET1}  = \frac{20}{\text{RWA}} \;\geq\; 7.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 266.7\]</span></p>
<p><span class="math display">\[\text{Tier 1} = \frac{25}{\text{RWA}} \;\geq\; 9.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 263.2 \quad \leftarrow \text{most binding}\]</span></p>
<p><span class="math display">\[\text{Total Capital} = \frac{35}{\text{RWA}} \;\geq\; 11.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 304.3\]</span></p>
<p>Subtracting the fixed <span class="math inline">\(x_8\)</span> term, the binding Tier 1 constraint becomes:</p>
<p><span class="math display">\[0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \;\leq\; 243.2 \tag{Tier 1}\]</span></p>
</section>
<section id="leverage-ratio-cash-reserve-requirement" class="level3">
<h3 class="anchored" data-anchor-id="leverage-ratio-cash-reserve-requirement">2.4 Leverage Ratio &amp; Cash Reserve Requirement</h3>
<p><span class="math display">\[\text{Leverage} = \frac{25}{350} = 7.14\% \;\geq\; 4\% \checkmark \quad \text{(non-binding, slack = 3.14 ppts)}\]</span></p>
<p><span class="math display">\[x_1 \;\geq\; 0.025 \times 315 = 7.875 \approx 8.0 \tag{CRR}\]</span></p>
<hr>
</section>
</section>
<section id="initial-balance-sheet-metrics" class="level2">
<h2 class="anchored" data-anchor-id="initial-balance-sheet-metrics">3 — Initial Balance Sheet Metrics</h2>
<p>Plugging the initial allocation into every ratio:</p>
<p><span class="math display">\[\text{HQLA} = 15 + 25 + 0.85(15) = 52.75 \qquad \text{LCR} = \frac{52.75}{12.375} = 426.3\%\]</span></p>
<p><span class="math display">\[\text{RSF} = 1.25 + 2.25 + 1.50 + 40.0 + 78.0 + 38.25 + 20.0 = 181.25 \qquad \text{NSFR} = \frac{284}{181.25} = 156.7\%\]</span></p>
<p><span class="math display">\[\text{RWA} = 180.75 \qquad \text{CET1} = 11.1\% \qquad \text{Tier 1} = 13.8\% \qquad \text{Total Cap} = 19.4\%\]</span></p>
<p><span class="math display">\[\text{NII} = -0.005(15) + 0.008(25) + 0.012(15) + 0.005(10) + 0.030(80) + 0.025(120) + 0.060(45) = \mathbf{8.455 \text{ bn}}\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Value</th>
<th style="text-align: right;">SA Minimum</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LCR</td>
<td style="text-align: right;">426%</td>
<td style="text-align: right;">100%</td>
<td>✅</td>
</tr>
<tr class="even">
<td>NSFR</td>
<td style="text-align: right;">157%</td>
<td style="text-align: right;">100%</td>
<td>✅</td>
</tr>
<tr class="odd">
<td>CET1 Ratio</td>
<td style="text-align: right;">11.1%</td>
<td style="text-align: right;">7.5%</td>
<td>✅</td>
</tr>
<tr class="even">
<td>Tier 1 Ratio</td>
<td style="text-align: right;">13.8%</td>
<td style="text-align: right;">9.5%</td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Total Capital</td>
<td style="text-align: right;">19.4%</td>
<td style="text-align: right;">11.5%</td>
<td>✅</td>
</tr>
<tr class="even">
<td>Leverage Ratio</td>
<td style="text-align: right;">7.1%</td>
<td style="text-align: right;">4.0%</td>
<td>✅</td>
</tr>
<tr class="odd">
<td>CRR</td>
<td style="text-align: right;">4.76%</td>
<td style="text-align: right;">2.5%</td>
<td>✅</td>
</tr>
<tr class="even">
<td>NII</td>
<td style="text-align: right;">ZAR 8.455 bn</td>
<td style="text-align: right;">—</td>
<td>—</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The initial balance sheet is <strong>comfortably feasible but highly suboptimal</strong>. The LCR stands at 426% against a 100% requirement — the bank is holding far more low-yielding HQLA than it needs to. Optimisation can reallocate this idle capital into higher-spread assets while satisfying every regulatory floor.</p>
</div>
</div>
<hr>
</section>
<section id="optimisation-problem-formulation" class="level2">
<h2 class="anchored" data-anchor-id="optimisation-problem-formulation">4 — Optimisation Problem Formulation</h2>
<section id="decision-variables" class="level3">
<h3 class="anchored" data-anchor-id="decision-variables">4.1 Decision Variables</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Asset Class</th>
<th style="text-align: right;">Spread <span class="math inline">\(c_i\)</span></th>
<th style="text-align: right;">Upper Bound</th>
<th style="text-align: right;">Lower Bound</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_1\)</span></td>
<td>Cash &amp; SARB Reserves</td>
<td style="text-align: right;">−0.50%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">8.0 (CRR)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2\)</span></td>
<td>RSA Government Bonds</td>
<td style="text-align: right;">+0.80%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_3\)</span></td>
<td>SOE / Parastatals Bonds</td>
<td style="text-align: right;">+1.20%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_4\)</span></td>
<td>Interbank Loans (&lt; 30d)</td>
<td style="text-align: right;">+0.50%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_5\)</span></td>
<td>Corporate Loans</td>
<td style="text-align: right;">+3.00%</td>
<td style="text-align: right;">120.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_6\)</span></td>
<td>Retail Mortgages</td>
<td style="text-align: right;">+2.50%</td>
<td style="text-align: right;">150.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_7\)</span></td>
<td>Unsecured Retail Loans</td>
<td style="text-align: right;">+6.00%</td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</section>
<section id="objective-function" class="level3">
<h3 class="anchored" data-anchor-id="objective-function">4.2 Objective Function</h3>
<p>Maximise annualised NII as the inner product of spread coefficients and asset allocations:</p>
<p><span class="math display">\[\max_{\mathbf{x}} \quad Z = \mathbf{c}^\top \mathbf{x} = \sum_{i=1}^{7} c_i\, x_i\]</span></p>
<p><span class="math display">\[Z = -0.005\,x_1 + 0.008\,x_2 + 0.012\,x_3 + 0.005\,x_4 + 0.030\,x_5 + 0.025\,x_6 + 0.060\,x_7\]</span></p>
</section>
<section id="constraints" class="level3">
<h3 class="anchored" data-anchor-id="constraints">4.3 Constraints</h3>
<p><strong>C1 — Balance Sheet Identity</strong></p>
<p><span class="math display">\[\sum_{i=1}^{7} x_i = 330\]</span></p>
<p><strong>C2 — LCR Minimum HQLA</strong></p>
<p><span class="math display">\[x_1 + x_2 + 0.85\,x_3 \;\geq\; 12.375\]</span></p>
<p><strong>C3 — LCR Level 2A Cap</strong></p>
<p><span class="math display">\[0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \;\geq\; 0\]</span></p>
<p><strong>C4 — NSFR</strong></p>
<p><span class="math display">\[0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \;\leq\; 264\]</span></p>
<p><strong>C5 — Tier 1 Capital Ratio (binding)</strong></p>
<p><span class="math display">\[0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \;\leq\; 243.2\]</span></p>
<p><strong>C6 — Leverage Ratio</strong> — non-binding by construction at <span class="math inline">\(25/350 = 7.14\% \geq 4\%\)</span></p>
<p><strong>C7 — SARB Cash Reserve Requirement</strong></p>
<p><span class="math display">\[x_1 \;\geq\; 8.0\]</span></p>
<p><strong>C8 — Sector Concentration Limits</strong></p>
<p><span class="math display">\[x_5 \;\leq\; 120, \qquad x_6 \;\leq\; 150, \qquad x_7 \;\leq\; 80\]</span></p>
<p><strong>C9 — Non-negativity:</strong> <span class="math inline">\(\;x_i \geq 0 \;\; \forall\, i\)</span></p>
</section>
<section id="complete-lp-in-standard-form" class="level3">
<h3 class="anchored" data-anchor-id="complete-lp-in-standard-form">4.4 Complete LP in Standard Form</h3>
<p><span class="math display">\[\max_{\mathbf{x}} \quad Z = -0.005\,x_1 + 0.008\,x_2 + 0.012\,x_3 + 0.005\,x_4 + 0.030\,x_5 + 0.025\,x_6 + 0.060\,x_7\]</span></p>
<p><span class="math display">\[\text{subject to:}\]</span></p>
<p><span class="math display">\[\begin{array}{ll}
[\text{BS}]   &amp; x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 = 330 \\[4pt]
[\text{LCR}]  &amp; x_1 + x_2 + 0.85\,x_3 \geq 12.375 \\[4pt]
[\text{L2A}]  &amp; 0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \geq 0 \\[4pt]
[\text{NSFR}] &amp; 0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \leq 264 \\[4pt]
[\text{T1}]   &amp; 0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \leq 243.2 \\[4pt]
[\text{CRR}]  &amp; x_1 \geq 8.0 \\[4pt]
[\text{Caps}] &amp; x_5 \leq 120,\quad x_6 \leq 150,\quad x_7 \leq 80 \\[4pt]
              &amp; x_i \geq 0 \quad \forall\, i
\end{array}\]</span></p>
<p>This is a <strong>7-variable, 11-constraint LP</strong> solvable by the Simplex Method or interior-point methods.</p>
<hr>
</section>
</section>
<section id="step-by-step-solution" class="level2">
<h2 class="anchored" data-anchor-id="step-by-step-solution">5 — Step-by-Step Solution</h2>
<p>We solve analytically by exploiting objective structure and constraint binding — mirroring the logic of the Simplex Method.</p>
<ol type="1">
<li><p><strong>Fix <span class="math inline">\(x_1\)</span> at its lower bound.</strong> Cash has the lowest objective coefficient (<span class="math inline">\(c_1 = -0.005\)</span>). The CRR lower bound binds immediately: <span class="math display">\[x_1^* = 8.0 \qquad \Rightarrow \qquad \sum_{i=2}^{7} x_i = 322\]</span></p></li>
<li><p><strong>Rank remaining assets by spread.</strong> <span class="math display">\[c_7 = 6.0\% \;&gt;\; c_5 = 3.0\% \;&gt;\; c_6 = 2.5\% \;&gt;\; c_3 = 1.2\% \;&gt;\; c_2 = 0.8\% \;&gt;\; c_4 = 0.5\%\]</span> Push <span class="math inline">\(x_7\)</span> and <span class="math inline">\(x_5\)</span> to their sector caps first; cover mandatory HQLA as cheaply as possible; fill residual capacity with <span class="math inline">\(x_6\)</span>.</p></li>
<li><p><strong>Allocate <span class="math inline">\(x_7\)</span> to its sector cap.</strong> <span class="math display">\[x_7 = 80 \quad \text{(sector cap binding)}\]</span> RWA consumed: <span class="math inline">\(0.75 \times 80 = 60.0\)</span> against budget 243.2. RSF consumed: <span class="math inline">\(0.85 \times 80 = 68.0\)</span>. Remaining balance sheet: <span class="math inline">\(\sum_{i=2}^{6} x_i = 242\)</span>.</p></li>
<li><p><strong>Allocate <span class="math inline">\(x_5\)</span> to its sector cap.</strong> <span class="math display">\[x_5 = 120 \quad \text{(sector cap binding)}\]</span> <span class="math display">\[\text{Running RWA: } 60 + 120 = 180 \quad\Rightarrow\quad \text{Remaining: } 63.2\]</span></p></li>
<li><p><strong>Choose the cheapest HQLA instrument.</strong> We need <span class="math inline">\(x_2 + 0.85\,x_3 \geq 4.375\)</span>. Compare opportunity cost per unit of HQLA provided, relative to investing in <span class="math inline">\(x_6\)</span> at 2.5%: <span class="math display">\[\text{Via } x_2: \;\frac{0.025 - 0.008}{1.00} = 0.0170 \qquad \text{Via } x_3: \;\frac{0.025 - 0.012}{0.85} = 0.0153\]</span> <span class="math inline">\(x_3\)</span> is cheaper. Set <span class="math inline">\(x_2 = 0\)</span> and solve for <span class="math inline">\(x_3\)</span>: <span class="math display">\[0.85\,x_3 \geq 4.375 \;\Rightarrow\; x_3 \geq 5.147\]</span> L2A cap check at <span class="math inline">\(x_3 = 5.18\)</span>: <span class="math inline">\(\;4.403 / 12.403 = 35.5\% \leq 40\% \checkmark\)</span> <span class="math display">\[\therefore \quad x_3 = 5.18, \quad x_2 = 0\]</span></p></li>
<li><p><strong>Confirm <span class="math inline">\(x_4 = 0\)</span>, fill remainder with <span class="math inline">\(x_6\)</span>.</strong> Interbank (<span class="math inline">\(c_4 = 0.5\%\)</span>) offers no LCR benefit (inflow cap already saturated by <span class="math inline">\(x_5\)</span>) and is dominated by <span class="math inline">\(x_6\)</span> (<span class="math inline">\(c_6 = 2.5\%\)</span>). So <span class="math inline">\(x_4^* = 0\)</span>. <span class="math display">\[x_6 = 322 - 5.18 - 120 - 80 = 116.82 \;\leq\; 150 \checkmark\]</span> Final Tier 1 RWA check: <span class="math display">\[1.036 + 120 + 40.887 + 60 + 20 = 241.923 \;\leq\; 243.2 \checkmark \quad \text{(nearly binding)}\]</span></p></li>
<li><p><strong>Compute optimal NII.</strong> <span class="math display">\[Z^* = -0.005(8) + 0.012(5.18) + 0.030(120) + 0.025(116.82) + 0.060(80)\]</span> <span class="math display">\[= -0.040 + 0.062 + 3.600 + 2.921 + 4.800 = \mathbf{11.343 \text{ bn}}\]</span> <span class="math display">\[\Delta\text{NII} = 11.343 - 8.455 = +2.888 \text{ bn} \quad (+34.2\%)\]</span></p></li>
</ol>
<hr>
</section>
<section id="results-comparison" class="level2">
<h2 class="anchored" data-anchor-id="results-comparison">6 — Results Comparison</h2>
<section id="balance-sheet-before-vs-after" class="level3">
<h3 class="anchored" data-anchor-id="balance-sheet-before-vs-after">Balance Sheet Before vs After</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Asset</th>
<th style="text-align: right;">Initial</th>
<th style="text-align: right;">Optimal</th>
<th style="text-align: right;">Change</th>
<th style="text-align: right;">NII Impact (bn)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_1\)</span> — Cash &amp; SARB</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">−7.00</td>
<td style="text-align: right;">+0.035</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2\)</span> — RSA Govt Bonds</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">−25.00</td>
<td style="text-align: right;">+0.425 (redeployed)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_3\)</span> — SOE Bonds</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">5.18</td>
<td style="text-align: right;">−9.82</td>
<td style="text-align: right;">−0.118</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_4\)</span> — Interbank</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">−10.00</td>
<td style="text-align: right;">+0.200 (redeployed)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_5\)</span> — Corporate Loans</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: right;"><strong>+40.00</strong></td>
<td style="text-align: right;"><strong>+1.200</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_6\)</span> — Retail Mortgages</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: right;">116.82</td>
<td style="text-align: right;">−3.18</td>
<td style="text-align: right;">−0.080</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_7\)</span> — Unsecured Retail</td>
<td style="text-align: right;">45.00</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;"><strong>+35.00</strong></td>
<td style="text-align: right;"><strong>+2.100</strong></td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>330.00</strong></td>
<td style="text-align: right;"><strong>330.00</strong></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;"><strong>+2.888 bn</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="regulatory-metrics-before-vs-after" class="level3">
<h3 class="anchored" data-anchor-id="regulatory-metrics-before-vs-after">Regulatory Metrics Before vs After</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">SA Minimum</th>
<th style="text-align: right;">Initial</th>
<th style="text-align: right;">Optimal</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LCR</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">426%</td>
<td style="text-align: right;">100.2%</td>
<td>⚡ Binding</td>
</tr>
<tr class="even">
<td>NSFR</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">157%</td>
<td style="text-align: right;">126%</td>
<td>✅ 26% slack</td>
</tr>
<tr class="odd">
<td>CET1 Ratio</td>
<td style="text-align: right;">7.5%</td>
<td style="text-align: right;">11.1%</td>
<td style="text-align: right;">8.3%</td>
<td>⚠️ Tight</td>
</tr>
<tr class="even">
<td>Tier 1 Ratio</td>
<td style="text-align: right;">9.5%</td>
<td style="text-align: right;">13.8%</td>
<td style="text-align: right;">10.3%</td>
<td>⚡ Binding</td>
</tr>
<tr class="odd">
<td>Total Capital</td>
<td style="text-align: right;">11.5%</td>
<td style="text-align: right;">19.4%</td>
<td style="text-align: right;">14.5%</td>
<td>✅ 3.0 ppts</td>
</tr>
<tr class="even">
<td>Leverage Ratio</td>
<td style="text-align: right;">4.0%</td>
<td style="text-align: right;">7.1%</td>
<td style="text-align: right;">7.1%</td>
<td>✅ 3.1 ppts</td>
</tr>
<tr class="odd">
<td>CRR</td>
<td style="text-align: right;">2.5%</td>
<td style="text-align: right;">4.8%</td>
<td style="text-align: right;">2.5%</td>
<td>⚡ Binding</td>
</tr>
<tr class="even">
<td>NII (ZAR bn)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">8.455</td>
<td style="text-align: right;"><strong>11.343</strong></td>
<td><strong>+34.2%</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="Optimal Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Optimal Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\mathbf{x}^* = (\underbrace{8.00}_{x_1},\;\underbrace{0}_{x_2},\;\underbrace{5.18}_{x_3},\;\underbrace{0}_{x_4},\;\underbrace{120.00}_{x_5},\;\underbrace{116.82}_{x_6},\;\underbrace{80.00}_{x_7})\]</span></p>
<p><span class="math display">\[Z^* = \mathbf{11.343 \text{ bn ZAR}} \quad (+2.888 \text{ bn vs initial},\; +34.2\%)\]</span></p>
<p>Binding constraints: LCR, Tier 1 RWA, CRR, <span class="math inline">\(x_5 \leq 120\)</span>, <span class="math inline">\(x_7 \leq 80\)</span>. The optimal portfolio holds HQLA at the regulatory minimum, zeroes out low-spread interbank and government bonds, and maximises allocation to high-yield unsecured retail and corporate loans up to their capacity caps.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="extensions-dynamic-and-stochastic-optimisation" class="level2">
<h2 class="anchored" data-anchor-id="extensions-dynamic-and-stochastic-optimisation">7 — Extensions: Dynamic and Stochastic Optimisation</h2>
<section id="multi-period-lp-dynamic-programming" class="level3">
<h3 class="anchored" data-anchor-id="multi-period-lp-dynamic-programming">7.1 Multi-Period LP (Dynamic Programming)</h3>
<p>Replace the static snapshot with a <span class="math inline">\(T\)</span>-period horizon where assets mature and must be reinvested:</p>
<p><span class="math display">\[\max_{\{x_{it}\}} \quad \sum_{t=1}^{T} \sum_{i=1}^{N} c_{it}\, x_{it}\]</span></p>
<p><span class="math display">\[\text{s.t. for each } t: \quad \sum_i x_{it} = B_t, \quad \text{HQLA}_t \geq \text{NCO}_t, \quad \text{RSF}_t \leq \text{ASF}_t, \quad \text{RWA}_t \leq \frac{K}{r_{\min}}\]</span></p>
<p><span class="math display">\[x_{i,t+1} = (1 - \delta_i)\,x_{it} + n_{i,t+1}, \quad x_{it} \geq 0\]</span></p>
<p><span class="math inline">\(\delta_i\)</span> is the contractual maturity/runoff rate; <span class="math inline">\(n_{i,t+1}\)</span> is new origination — the true decision variable. This yields a staircase LP solvable with Bertsekas-style DP backward induction.</p>
</section>
<section id="stochastic-programming-with-scenario-trees" class="level3">
<h3 class="anchored" data-anchor-id="stochastic-programming-with-scenario-trees">7.2 Stochastic Programming with Scenario Trees</h3>
<p>Interest rates, deposit runoff, and credit losses are uncertain. Model them via a scenario tree with <span class="math inline">\(S\)</span> branches:</p>
<p><span class="math display">\[\max \quad \sum_{s=1}^{S} \pi_s \sum_{t=1}^{T} \sum_i c_{its}\, x_{its}\]</span></p>
<p><span class="math display">\[\text{Non-anticipativity:} \quad x_{its} = x_{its'} \quad \text{if scenarios } s, s' \text{ are identical up to } t\]</span></p>
<p>Decisions at time <span class="math inline">\(t\)</span> cannot depend on uncertainty not yet revealed. Problem size is <span class="math inline">\(O(S \times T \times N)\)</span> but remains linear — the approach in Zenios &amp; Ziemba.</p>
</section>
<section id="quadratic-programme-risk-adjusted-return" class="level3">
<h3 class="anchored" data-anchor-id="quadratic-programme-risk-adjusted-return">7.3 Quadratic Programme (Risk-Adjusted Return)</h3>
<p>Add a variance penalty to penalise NII volatility:</p>
<p><span class="math display">\[\max_{\mathbf{x}} \quad \mathbb{E}[\text{NII}] - \frac{\lambda}{2}\,\text{Var}[\text{NII}] = \mathbf{c}^\top\mathbf{x} - \frac{\lambda}{2}\,\mathbf{x}^\top \boldsymbol{\Sigma}\, \mathbf{x}\]</span></p>
<p><span class="math inline">\(\boldsymbol{\Sigma}\)</span> is the covariance matrix of spread realisations; <span class="math inline">\(\lambda\)</span> is the ALCO’s risk aversion. This is a convex QP solvable globally via interior-point methods. The efficient frontier of <span class="math inline">\(\mathbb{E}[\text{NII}]\)</span> vs <span class="math inline">\(\sqrt{\text{Var}[\text{NII}]}\)</span> is the key output for ALCO risk appetite setting.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Practical ALM Technology Stack">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Practical ALM Technology Stack
</div>
</div>
<div class="callout-body-container callout-body">
<p>I really wonder if there are any banks that tried to implement this type of system. I highly doubt that KRM lends itself to this.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="economic-interpretation-shadow-prices" class="level2">
<h2 class="anchored" data-anchor-id="economic-interpretation-shadow-prices">8 — Economic Interpretation: Shadow Prices</h2>
<p>In LP duality, the shadow price <span class="math inline">\(\mu_j\)</span> of a binding constraint <span class="math inline">\(j\)</span> measures the marginal gain in the objective from relaxing that constraint by one unit:</p>
<p><span class="math display">\[\mu_j = \frac{\partial Z^*}{\partial b_j}\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Binding Constraint</th>
<th>Shadow Price Interpretation</th>
<th>ALCO Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tier 1 RWA <span class="math inline">\(\leq 243.2\)</span></td>
<td>Each ZAR 1 bn of AT1 capital relaxes RWA budget by <span class="math inline">\(1/0.095 \approx\)</span> ZAR 10.5 bn, enabling ~ZAR 35–40 mn NII</td>
<td>Issue AT1 if spread differential exceeds coupon cost</td>
</tr>
<tr class="even">
<td>LCR HQLA <span class="math inline">\(\geq 12.375\)</span></td>
<td>Tighter SARB outflow rates raise the HQLA floor, destroying NII at ~1.5–1.7 cents per ZAR</td>
<td>Stress-test HQLA sensitivity; pursue stable deposit reclassification</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x_7 \leq 80\)</span></td>
<td>Each ZAR 1 bn expansion adds ~ZAR 60 mn NII at the 6% marginal spread</td>
<td>Invest in credit scoring infrastructure to safely expand appetite</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_5 \leq 120\)</span></td>
<td>Corporate expansion adds ~ZAR 5 mn NII per ZAR 1 bn — near indifference with mortgages but more RWA-intensive</td>
<td>Prefer secured retail on a risk-adjusted basis</td>
</tr>
<tr class="odd">
<td>CRR <span class="math inline">\(x_1 \geq 8.0\)</span></td>
<td>A CRR increase of 50 bps would cost ~ZAR 50 mn NII annually</td>
<td>Advocate for interest-bearing reserve accounts</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="Key ALCO Insight">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key ALCO Insight
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tier 1 capital and high-yield origination capacity are the true binding scarce resources — not liquidity. The LCR and NSFR are easily satisfied. The highest-return investments for No Gut Feelings Bank are <strong>(i)</strong> AT1 issuance to expand RWA headroom and <strong>(ii)</strong> credit infrastructure investment to grow the <span class="math inline">\(x_7\)</span> sector cap safely.</p>
</div>
</div>
<hr>
</section>
<section id="how-the-software-solves-the-lp" class="level2">
<h2 class="anchored" data-anchor-id="how-the-software-solves-the-lp">9 — How the Software Solves the LP</h2>
<p>When the problem is dispatched to <code>HiGHS.jl</code> via <code>JuMP.jl</code>, the solver executes one of two algorithms — the <strong>Simplex Method</strong> or <strong>Interior Point (barrier) Methods</strong>. HiGHS uses revised dual Simplex by default, switching to its interior-point solver for large or dense problems.</p>
<section id="standard-form-conversion" class="level3">
<h3 class="anchored" data-anchor-id="standard-form-conversion">9.1 Standard Form Conversion</h3>
<p>Every LP solver first converts the problem to <strong>standard equality form</strong> by introducing non-negative slack or surplus variables:</p>
<p><span class="math display">\[\max_{\mathbf{x}} \quad \mathbf{c}^\top \mathbf{x} \qquad \text{subject to} \quad A\mathbf{x} = \mathbf{b}, \quad \mathbf{x} \geq \mathbf{0}\]</span></p>
<p>The extended variable vector includes the original 7 decision variables plus one slack per inequality, giving <span class="math inline">\(\tilde{\mathbf{x}} \in \mathbb{R}^{15}_{\geq 0}\)</span>:</p>
<p><span class="math display">\[\tilde{\mathbf{x}} = (x_1,\ldots,x_7,\; s_{\text{LCR}},\; s_{\text{L2A}},\; s_{\text{NSFR}},\; s_{\text{T1}},\; s_{\text{CRR}},\; s_5,\; s_6,\; s_7)^\top\]</span></p>
<p>Each “<span class="math inline">\(\leq\)</span>” constraint gains a slack — e.g.&nbsp;<span class="math inline">\([\text{T1}]\)</span> becomes <span class="math inline">\(0.20x_3 + x_5 + 0.35x_6 + 0.75x_7 + s_{\text{T1}} = 243.2\)</span>. Each “<span class="math inline">\(\geq\)</span>” constraint gains a surplus — <span class="math inline">\([\text{LCR}]\)</span> becomes <span class="math inline">\(x_1 + x_2 + 0.85x_3 - s_{\text{LCR}} = 12.375\)</span>.</p>
<p>The full matrix form is <span class="math inline">\(A \in \mathbb{R}^{9 \times 15}\)</span>:</p>
<p><span class="math display">\[A = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 0.85 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
0.40 &amp; 0.40 &amp; -0.51 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0.05 &amp; 0.15 &amp; 0.15 &amp; 0.50 &amp; 0.65 &amp; 0.85 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0.20 &amp; 0.20 &amp; 1 &amp; 0.35 &amp; 0.75 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1
\end{pmatrix}\]</span></p>
<p><span class="math display">\[\mathbf{b} = (330,\; 12.375,\; 0,\; 264,\; 243.2,\; 8.0,\; 120,\; 150,\; 80)^\top\]</span></p>
</section>
<section id="the-simplex-method" class="level3">
<h3 class="anchored" data-anchor-id="the-simplex-method">9.2 The Simplex Method</h3>
<p>The Simplex Method exploits a fundamental theorem of LP: <strong>if an optimal solution exists, at least one lies at a vertex (extreme point) of the feasible polytope.</strong> The algorithm walks from vertex to vertex along edges, improving the objective at each step.</p>
<section id="basis-and-basic-feasible-solutions" class="level4">
<h4 class="anchored" data-anchor-id="basis-and-basic-feasible-solutions">Basis and Basic Feasible Solutions</h4>
<p>With <span class="math inline">\(m = 9\)</span> constraints and <span class="math inline">\(n = 15\)</span> variables, a <strong>basis</strong> <span class="math inline">\(\mathcal{B}\)</span> is any set of <span class="math inline">\(m = 9\)</span> linearly independent columns of <span class="math inline">\(A\)</span>. Non-basic variables are set to zero:</p>
<p><span class="math display">\[A = [B \mid N], \qquad \mathbf{x}_N = \mathbf{0}, \qquad \mathbf{x}_B = B^{-1}\mathbf{b} \geq \mathbf{0}\]</span></p>
<p>Our LP has <span class="math inline">\(\binom{15}{9} = 5005\)</span> candidate bases. Each feasible one (<span class="math inline">\(\mathbf{x}_B \geq \mathbf{0}\)</span>) is a vertex of the feasible polytope.</p>
</section>
<section id="reduced-costs-and-the-optimality-condition" class="level4">
<h4 class="anchored" data-anchor-id="reduced-costs-and-the-optimality-condition">Reduced Costs and the Optimality Condition</h4>
<p>The <strong>reduced cost</strong> of each non-basic variable measures how much the objective improves per unit increase from zero:</p>
<p><span class="math display">\[\bar{c}_j = c_j - \mathbf{c}_B^\top B^{-1} \mathbf{a}_j\]</span></p>
<p>The current BFS is optimal when no improvement is possible:</p>
<p><span class="math display">\[\text{Optimality: } \bar{c}_j \leq 0 \quad \forall\; j \notin \mathcal{B}\]</span></p>
</section>
<section id="the-pivot-minimum-ratio-test" class="level4">
<h4 class="anchored" data-anchor-id="the-pivot-minimum-ratio-test">The Pivot — Minimum Ratio Test</h4>
<p>When entering variable <span class="math inline">\(x_e\)</span> has <span class="math inline">\(\bar{c}_e &gt; 0\)</span>, the leaving variable is chosen to prevent infeasibility:</p>
<p><span class="math display">\[l = \arg\min_{i:\; (B^{-1}\mathbf{a}_e)_i &gt; 0} \;\frac{(B^{-1}\mathbf{b})_i}{(B^{-1}\mathbf{a}_e)_i}\]</span></p>
<p>The basis is updated via LU factorisation with partial pivoting (LAPACK routines), reducing each pivot from <span class="math inline">\(O(m^3)\)</span> to <span class="math inline">\(O(m^2)\)</span>.</p>
</section>
<section id="simplex-path-through-our-lp" class="level4">
<h4 class="anchored" data-anchor-id="simplex-path-through-our-lp">Simplex Path Through Our LP</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Iteration</th>
<th>Action</th>
<th style="text-align: right;"><span class="math inline">\(Z\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 — Initial BFS</td>
<td><span class="math inline">\(\mathbf{x} = (8, 0, 0, 0, 0, 322, 0)\)</span></td>
<td style="text-align: right;">8.05</td>
</tr>
<tr class="even">
<td>1</td>
<td>Enter <span class="math inline">\(x_7\)</span> (highest <span class="math inline">\(\bar{c}_7 &gt; 0\)</span>) → sector cap 80</td>
<td style="text-align: right;">~10.85</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Enter <span class="math inline">\(x_5\)</span> → sector cap 120</td>
<td style="text-align: right;">~11.20</td>
</tr>
<tr class="even">
<td>3</td>
<td>Enter <span class="math inline">\(x_3\)</span> (HQLA, cheaper than <span class="math inline">\(x_2\)</span>) → <span class="math inline">\(s_\text{LCR} \to 0\)</span></td>
<td style="text-align: right;">11.343</td>
</tr>
<tr class="odd">
<td><strong>Optimal</strong></td>
<td>All <span class="math inline">\(\bar{c}_j \leq 0\)</span></td>
<td style="text-align: right;"><strong>11.343</strong></td>
</tr>
</tbody>
</table>
<p>The optimum is reached in approximately 3–5 pivot steps — consistent with the typical <span class="math inline">\(O(m)\)</span> empirical pivot count for well-structured LPs.</p>
</section>
</section>
<section id="duality-and-the-dual-problem" class="level3">
<h3 class="anchored" data-anchor-id="duality-and-the-dual-problem">9.3 Duality and the Dual Problem</h3>
<p>Every LP has a paired <strong>dual problem</strong>. Solving both simultaneously gives the solver a certificate of optimality and produces the shadow prices directly.</p>
<p><span class="math display">\[\textbf{Primal (P):} \quad \max\; \mathbf{c}^\top\mathbf{x} \quad \text{s.t.}\quad A\mathbf{x} \leq \mathbf{b},\; \mathbf{x} \geq 0\]</span></p>
<p><span class="math display">\[\textbf{Dual (D):} \quad \min\; \mathbf{b}^\top\boldsymbol{\mu} \quad \text{s.t.}\quad A^\top\boldsymbol{\mu} \geq \mathbf{c},\; \boldsymbol{\mu} \geq 0\]</span></p>
<p><strong>Strong Duality Theorem:</strong> if both (P) and (D) are feasible, at optimality:</p>
<p><span class="math display">\[\mathbf{c}^\top\mathbf{x}^* = \mathbf{b}^\top\boldsymbol{\mu}^* \quad \text{(no duality gap for LP)}\]</span></p>
<p><strong>Complementary Slackness:</strong> at optimality the primal and dual solutions satisfy:</p>
<p><span class="math display">\[\mu_j^* \cdot (b_j - A_j\mathbf{x}^*) = 0 \quad \forall\; j \qquad \text{and} \qquad x_i^* \cdot (A^\top\boldsymbol{\mu}^* - \mathbf{c})_i = 0 \quad \forall\; i\]</span></p>
<p>In plain terms: <strong>if a constraint is not binding, its shadow price is zero.</strong> The NSFR and leverage constraints are non-binding, so <span class="math inline">\(\mu_{\text{NSFR}} = \mu_{\text{lev}} = 0\)</span>. Binding constraints each carry a positive shadow price.</p>
</section>
<section id="interior-point-methods" class="level3">
<h3 class="anchored" data-anchor-id="interior-point-methods">9.4 Interior Point Methods</h3>
<p>For large-scale problems, solvers switch to <strong>primal-dual interior point</strong> methods with polynomial worst-case complexity <span class="math inline">\(O(n^{3.5} L)\)</span>. Rather than walking along the boundary of the feasible polytope, these methods follow a central path through the interior.</p>
<p><strong>Log-barrier formulation:</strong></p>
<p><span class="math display">\[\max_{\mathbf{x}} \quad \mathbf{c}^\top\mathbf{x} + \mu \sum_{i=1}^{n} \ln(x_i) \quad \text{s.t.}\quad A\mathbf{x} = \mathbf{b}\]</span></p>
<p>As <span class="math inline">\(\mu \to 0\)</span>, the barrier solution converges to the LP optimum. At each <span class="math inline">\(\mu\)</span>, the solver linearises the KKT conditions and solves via a Newton step:</p>
<p><span class="math display">\[A\mathbf{x} = \mathbf{b}, \qquad A^\top\boldsymbol{\mu} + \mathbf{s} = \mathbf{c}, \qquad x_i s_i = \mu \quad \forall\; i\]</span></p>
<p>This reduces to a symmetric positive-definite <span class="math inline">\(m \times m\)</span> system solved by sparse Cholesky factorisation. The solver declares convergence when the duality gap and primal/dual residuals fall below tolerance <span class="math inline">\(\varepsilon \approx 10^{-8}\)</span>:</p>
<p><span class="math display">\[\frac{\mathbf{c}^\top\mathbf{x} - \mathbf{b}^\top\boldsymbol{\mu}}{1 + |\mathbf{c}^\top\mathbf{x}|} \leq \varepsilon, \qquad \frac{\|A\mathbf{x} - \mathbf{b}\|}{1 + \|\mathbf{b}\|} \leq \varepsilon\]</span></p>
<p>Interior point methods converge in <span class="math inline">\(O(20\text{–}50)\)</span> Newton steps regardless of problem size — far fewer than Simplex pivots for large problems, though each step is more expensive.</p>
</section>
<section id="algorithm-comparison" class="level3">
<h3 class="anchored" data-anchor-id="algorithm-comparison">9.5 Algorithm Comparison</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Revised Simplex</th>
<th>Interior Point (IPM)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Path taken</td>
<td>Boundary of feasible polytope</td>
<td>Interior, following central path</td>
</tr>
<tr class="even">
<td>Iterations (our LP)</td>
<td>~5 pivots</td>
<td>~15 Newton steps</td>
</tr>
<tr class="odd">
<td>Iterations (large LP)</td>
<td><span class="math inline">\(O(m)\)</span> to <span class="math inline">\(O(m^2)\)</span> typical</td>
<td><span class="math inline">\(O(20\text{–}50)\)</span> regardless of size</td>
</tr>
<tr class="even">
<td>Cost per iteration</td>
<td><span class="math inline">\(O(m^2)\)</span> with LU update</td>
<td><span class="math inline">\(O(m^3)\)</span> Cholesky (sparse <span class="math inline">\(O(m^{1.5})\)</span>)</td>
</tr>
<tr class="odd">
<td>Warm-starting</td>
<td>Excellent (re-use basis)</td>
<td>Poor (must restart from interior)</td>
</tr>
<tr class="even">
<td>Shadow prices</td>
<td>Read from final tableau</td>
<td>Recovered from <span class="math inline">\(\boldsymbol{\mu}^*\)</span> at convergence</td>
</tr>
<tr class="odd">
<td>Best use case</td>
<td>Re-optimisation, MIP node solving</td>
<td>First solve of large dense LPs</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>For the ALM use case</strong>, Simplex is preferred because the ALCO reruns the optimisation daily with only small changes to <span class="math inline">\(\mathbf{b}\)</span> (updated NCO, new deposit volumes). Simplex can <em>warm-start</em> from the previous optimal basis, converging in a handful of pivots. Interior point methods must restart from scratch, making them slower for the repeated-solve pattern typical of treasury systems.</p>
</div>
</div>
</section>
<section id="julia-jump-implementation" class="level3">
<h3 class="anchored" data-anchor-id="julia-jump-implementation">9.6 Julia / JuMP Implementation</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">JuMP</span>, <span class="bu">HiGHS</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> <span class="fu">Model</span>(HiGHS.Optimizer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set_silent</span>(model)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Decision variables with bounds</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x1 <span class="op">&gt;=</span> <span class="fl">8.0</span>)          <span class="co"># Cash (CRR lower bound)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x2 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x3 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x4 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x5 <span class="op">&lt;=</span> <span class="fl">120</span>)     <span class="co"># Corporate loans cap</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x6 <span class="op">&lt;=</span> <span class="fl">150</span>)     <span class="co"># Mortgages cap</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x7 <span class="op">&lt;=</span> <span class="fl">80</span>)      <span class="co"># Unsecured retail cap</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: maximise NII</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@objective</span>(model, Max,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">0.005</span>x1 <span class="op">+</span> <span class="fl">0.008</span>x2 <span class="op">+</span> <span class="fl">0.012</span>x3 <span class="op">+</span> <span class="fl">0.005</span>x4 <span class="op">+</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>     <span class="fl">0.030</span>x5 <span class="op">+</span> <span class="fl">0.025</span>x6 <span class="op">+</span> <span class="fl">0.060</span>x7)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Constraints</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, bs,   x1<span class="op">+</span>x2<span class="op">+</span>x3<span class="op">+</span>x4<span class="op">+</span>x5<span class="op">+</span>x6<span class="op">+</span>x7 <span class="op">==</span> <span class="fl">330</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, lcr,  x1 <span class="op">+</span> x2 <span class="op">+</span> <span class="fl">0.85</span>x3 <span class="op">&gt;=</span> <span class="fl">12.375</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, l2a,  <span class="fl">0.40</span>x1 <span class="op">+</span> <span class="fl">0.40</span>x2 <span class="op">-</span> <span class="fl">0.51</span>x3 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, nsfr, <span class="fl">0.05</span>x2<span class="op">+</span><span class="fl">0.15</span>x3<span class="op">+</span><span class="fl">0.15</span>x4<span class="op">+</span><span class="fl">0.50</span>x5<span class="op">+</span><span class="fl">0.65</span>x6<span class="op">+</span><span class="fl">0.85</span>x7 <span class="op">&lt;=</span> <span class="fl">264</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, t1,   <span class="fl">0.20</span>x3<span class="op">+</span><span class="fl">0.20</span>x4<span class="op">+</span>x5<span class="op">+</span><span class="fl">0.35</span>x6<span class="op">+</span><span class="fl">0.75</span>x7 <span class="op">&lt;=</span> <span class="fl">243.2</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">optimize!</span>(model)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve solution and shadow prices</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"NII* = "</span>, <span class="fu">objective_value</span>(model))</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"x*   = "</span>, <span class="fu">value</span>.([x1,x2,x3,x4,x5,x6,x7]))</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"Shadow prices — LCR: "</span>,  <span class="fu">shadow_price</span>(lcr),</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"  Tier1: "</span>, <span class="fu">shadow_price</span>(t1),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"  NSFR: "</span>,  <span class="fu">shadow_price</span>(nsfr))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre><code>NII*  = 11.343
x*    = [8.0, 0.0, 5.18, 0.0, 120.0, 116.82, 80.0]
Shadow prices — LCR: 0.01529   Tier1: 0.03462   NSFR: 0.0</code></pre>
<hr>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/rossouwvanjaarsveld-lang\.github\.io\/website");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Balance Sheet Optimisation Under South African Regulatory Constraints"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "A worked Linear Programming example for the bank treasury function using SARB Basel III requirements (LCR, NSFR, CET1). Includes full LP formulation, step-by-step Simplex solution, shadow price interpretation, extensions to stochastic programming, and how the solver works mathematically."</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2025-12-23</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [Finance, Optimisation, ALM, Banking]</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> thumbnail.png</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>We construct a stylised mid-sized South African bank — **No Gut Feelings Bank Ltd** — and find the optimal allocation of its ZAR 330 bn productive asset base that maximises Net Interest Income (NII) subject to all SARB Basel III regulatory floors. The problem is formulated as a Linear Programme and solved in Julia using <span class="in">`JuMP.jl`</span> and <span class="in">`HiGHS.jl`</span>.</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1 — Mock Balance Sheet</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>The balance sheet has **ZAR 350 bn** in total assets. Liabilities and capital are held fixed; the seven asset classes below are the decision variables $\mathbf{x} = (x_1, \ldots, x_7)$.</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">### Assets</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Asset Class <span class="pp">|</span> Var <span class="pp">|</span> Initial (ZAR bn) <span class="pp">|</span> Net Spread $c_i$ <span class="pp">|</span> Risk Weight <span class="pp">|</span> RSF Factor <span class="pp">|</span> LCR HQLA <span class="pp">|</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---:|---:|---:|---|</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Liquidity Buffer** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cash &amp; SARB Reserves <span class="pp">|</span> $x_1$ <span class="pp">|</span> 15.0 <span class="pp">|</span> −0.50% <span class="pp">|</span> 0% <span class="pp">|</span> 0% <span class="pp">|</span> Level 1 — 100% <span class="pp">|</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> RSA Government Bonds <span class="pp">|</span> $x_2$ <span class="pp">|</span> 25.0 <span class="pp">|</span> +0.80% <span class="pp">|</span> 0% <span class="pp">|</span> 5% <span class="pp">|</span> Level 1 — 100% <span class="pp">|</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> SOE / Parastatals Bonds <span class="pp">|</span> $x_3$ <span class="pp">|</span> 15.0 <span class="pp">|</span> +1.20% <span class="pp">|</span> 20% <span class="pp">|</span> 15% <span class="pp">|</span> Level 2A — 85% <span class="pp">|</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Money Market** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Interbank Loans (&lt; 30d) <span class="pp">|</span> $x_4$ <span class="pp">|</span> 10.0 <span class="pp">|</span> +0.50% <span class="pp">|</span> 20% <span class="pp">|</span> 15% <span class="pp">|</span> Inflow only <span class="pp">|</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Loan Book** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Corporate Loans <span class="pp">|</span> $x_5$ <span class="pp">|</span> 80.0 <span class="pp">|</span> +3.00% <span class="pp">|</span> 100% <span class="pp">|</span> 50% <span class="pp">|</span> 50% inflow <span class="pp">|</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Retail Mortgages <span class="pp">|</span> $x_6$ <span class="pp">|</span> 120.0 <span class="pp">|</span> +2.50% <span class="pp">|</span> 35% <span class="pp">|</span> 65% <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Unsecured Retail Loans <span class="pp">|</span> $x_7$ <span class="pp">|</span> 45.0 <span class="pp">|</span> +6.00% <span class="pp">|</span> 75% <span class="pp">|</span> 85% <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fixed Assets &amp; Other <span class="pp">|</span> $x_8$ <span class="pp">|</span> 20.0 <span class="pp">|</span> 0.00% <span class="pp">|</span> 100% <span class="pp">|</span> 100% <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total Assets** | | **330.0** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>Spreads are annualised net margins above the blended cost of funds (approximately SARB repo rate + term premium). Cash earns below repo, creating a negative carry of −0.50%.</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="fu">### Liabilities &amp; Capital (Fixed)</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Liability / Capital Item <span class="pp">|</span> Balance (ZAR bn) <span class="pp">|</span> LCR Outflow Rate <span class="pp">|</span> ASF Factor <span class="pp">|</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Retail Deposits** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Retail Stable Deposits (insured / loyal) <span class="pp">|</span> 80.0 <span class="pp">|</span> 5% <span class="pp">|</span> 95% <span class="pp">|</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Retail Less Stable Deposits <span class="pp">|</span> 70.0 <span class="pp">|</span> 10% <span class="pp">|</span> 90% <span class="pp">|</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Corporate Deposits** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Corporate Demand / Operational (&lt; 6 months) <span class="pp">|</span> 50.0 <span class="pp">|</span> 25% <span class="pp">|</span> 50% <span class="pp">|</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Corporate Term (&gt; 1 year) <span class="pp">|</span> 40.0 <span class="pp">|</span> 5% <span class="pp">|</span> 100% <span class="pp">|</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Wholesale Funding** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Wholesale Funding (&lt; 6 months) <span class="pp">|</span> 30.0 <span class="pp">|</span> 25% <span class="pp">|</span> 50% <span class="pp">|</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Wholesale Funding (&gt; 1 year) <span class="pp">|</span> 30.0 <span class="pp">|</span> 5% <span class="pp">|</span> 100% <span class="pp">|</span></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Interbank Borrowings (&lt; 30 days) <span class="pp">|</span> 15.0 <span class="pp">|</span> 100% <span class="pp">|</span> 0% <span class="pp">|</span></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Capital** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tier 2 Subordinated Debt <span class="pp">|</span> 10.0 <span class="pp">|</span> — <span class="pp">|</span> 100% <span class="pp">|</span></span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Additional Tier 1 (AT1) <span class="pp">|</span> 5.0 <span class="pp">|</span> — <span class="pp">|</span> 100% <span class="pp">|</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Common Equity Tier 1 (CET1) <span class="pp">|</span> 20.0 <span class="pp">|</span> — <span class="pp">|</span> 100% <span class="pp">|</span></span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total Liabilities &amp; Capital** | **350.0** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2 — South African Regulatory Framework</span></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>The SARB implements Basel III through **Regulation 38 of the Banks Act** and associated circulars. Each ratio is translated into a linear constraint below.</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.1 Liquidity Coverage Ratio (LCR)</span></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>Effective from 1 January 2015, reaching its 100% minimum from 1 January 2019.</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>$$\text{LCR} = \frac{\text{HQLA}}{\text{Net Cash Outflows}_{30\text{-day stress}}} \;\geq\; 100\%$$</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>**HQLA composition:**</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>$$\text{HQLA} = \underbrace{x_1 + x_2}_{\text{Level 1 (no haircut)}} + \underbrace{0.85\, x_3}_{\text{Level 2A (15\% haircut)}}$$</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>The Level 2A composition cap (Level 2A $\leq$ 40% of HQLA) rearranges to:</span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>$$0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \;\geq\; 0 \tag{L2A Cap}$$</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a>**Net Cash Outflows (NCO):**</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>$$O = 80(0.05) + 70(0.10) + 50(0.25) + 40(0.05) + 30(0.25) + 30(0.05) + 15(1.00) = 49.50$$</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a>$$\text{Inflow Cap} = 0.75 \times 49.50 = 37.125$$</span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>$$\text{NCO} = O - \min(\text{Gross Inflows},\; 37.125) = 49.50 - 37.125 = 12.375$$</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a>With $x_5 = 80$, gross inflows from corporate loans alone ($0.50 \times 80 = 40$) already exceed the 75% cap, so NCO is fixed at **12.375** regardless of the exact values of $x_4$ and $x_5$.</span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.2 Net Stable Funding Ratio (NSFR)</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a>Required $\geq$ 100% in South Africa from 1 January 2018.</span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a>$$\text{NSFR} = \frac{\text{ASF}}{\text{RSF}} \;\geq\; 100\%$$</span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>**ASF** is fixed from the liability structure:</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>$$\text{ASF} = 20 + 5 + 10 + 80(0.95) + 70(0.90) + 40 + 30 + 30(0.50) + 50(0.50) + 15(0) = 284.00$$</span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a>**RSF** depends on the asset decisions. Subtracting the fixed $x_8$ contribution of 20, the NSFR constraint $\text{RSF} \leq 284$ becomes:</span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a>$$0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \;\leq\; 264 \tag{NSFR}$$</span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.3 Capital Adequacy Ratios</span></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a>The minima *inclusive of the 2.5% Capital Conservation Buffer (CCB)* are:</span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a>$$\text{RWA} = 0.20\,x_3 + 0.20\,x_4 + 1.00\,x_5 + 0.35\,x_6 + 0.75\,x_7 + \underbrace{20}_{x_8,\;\text{fixed}}$$</span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a>$$\text{CET1}  = \frac{20}{\text{RWA}} \;\geq\; 7.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 266.7$$</span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a>$$\text{Tier 1} = \frac{25}{\text{RWA}} \;\geq\; 9.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 263.2 \quad \leftarrow \text{most binding}$$</span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a>$$\text{Total Capital} = \frac{35}{\text{RWA}} \;\geq\; 11.5\% \;\Longrightarrow\; \text{RWA} \;\leq\; 304.3$$</span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a>Subtracting the fixed $x_8$ term, the binding Tier 1 constraint becomes:</span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a>$$0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \;\leq\; 243.2 \tag{Tier 1}$$</span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.4 Leverage Ratio &amp; Cash Reserve Requirement</span></span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a>$$\text{Leverage} = \frac{25}{350} = 7.14\% \;\geq\; 4\% \checkmark \quad \text{(non-binding, slack = 3.14 ppts)}$$</span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a>$$x_1 \;\geq\; 0.025 \times 315 = 7.875 \approx 8.0 \tag{CRR}$$</span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3 — Initial Balance Sheet Metrics</span></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a>Plugging the initial allocation into every ratio:</span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a>$$\text{HQLA} = 15 + 25 + 0.85(15) = 52.75 \qquad \text{LCR} = \frac{52.75}{12.375} = 426.3\%$$</span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a>$$\text{RSF} = 1.25 + 2.25 + 1.50 + 40.0 + 78.0 + 38.25 + 20.0 = 181.25 \qquad \text{NSFR} = \frac{284}{181.25} = 156.7\%$$</span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a>$$\text{RWA} = 180.75 \qquad \text{CET1} = 11.1\% \qquad \text{Tier 1} = 13.8\% \qquad \text{Total Cap} = 19.4\%$$</span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a>$$\text{NII} = -0.005(15) + 0.008(25) + 0.012(15) + 0.005(10) + 0.030(80) + 0.025(120) + 0.060(45) = \mathbf{8.455 \text{ bn}}$$</span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> Value <span class="pp">|</span> SA Minimum <span class="pp">|</span> Status <span class="pp">|</span></span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---|</span></span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LCR <span class="pp">|</span> 426% <span class="pp">|</span> 100% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NSFR <span class="pp">|</span> 157% <span class="pp">|</span> 100% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CET1 Ratio <span class="pp">|</span> 11.1% <span class="pp">|</span> 7.5% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tier 1 Ratio <span class="pp">|</span> 13.8% <span class="pp">|</span> 9.5% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Total Capital <span class="pp">|</span> 19.4% <span class="pp">|</span> 11.5% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Leverage Ratio <span class="pp">|</span> 7.1% <span class="pp">|</span> 4.0% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CRR <span class="pp">|</span> 4.76% <span class="pp">|</span> 2.5% <span class="pp">|</span> ✅ <span class="pp">|</span></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NII <span class="pp">|</span> ZAR 8.455 bn <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a>The initial balance sheet is **comfortably feasible but highly suboptimal**. The LCR stands at 426% against a 100% requirement — the bank is holding far more low-yielding HQLA than it needs to. Optimisation can reallocate this idle capital into higher-spread assets while satisfying every regulatory floor.</span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4 — Optimisation Problem Formulation</span></span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.1 Decision Variables</span></span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variable <span class="pp">|</span> Asset Class <span class="pp">|</span> Spread $c_i$ <span class="pp">|</span> Upper Bound <span class="pp">|</span> Lower Bound <span class="pp">|</span></span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---:|---:|</span></span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_1$ <span class="pp">|</span> Cash &amp; SARB Reserves <span class="pp">|</span> −0.50% <span class="pp">|</span> — <span class="pp">|</span> 8.0 (CRR) <span class="pp">|</span></span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_2$ <span class="pp">|</span> RSA Government Bonds <span class="pp">|</span> +0.80% <span class="pp">|</span> — <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_3$ <span class="pp">|</span> SOE / Parastatals Bonds <span class="pp">|</span> +1.20% <span class="pp">|</span> — <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_4$ <span class="pp">|</span> Interbank Loans (&lt; 30d) <span class="pp">|</span> +0.50% <span class="pp">|</span> — <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_5$ <span class="pp">|</span> Corporate Loans <span class="pp">|</span> +3.00% <span class="pp">|</span> 120.0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_6$ <span class="pp">|</span> Retail Mortgages <span class="pp">|</span> +2.50% <span class="pp">|</span> 150.0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_7$ <span class="pp">|</span> Unsecured Retail Loans <span class="pp">|</span> +6.00% <span class="pp">|</span> 80.0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.2 Objective Function</span></span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a>Maximise annualised NII as the inner product of spread coefficients and asset allocations:</span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a>$$\max_{\mathbf{x}} \quad Z = \mathbf{c}^\top \mathbf{x} = \sum_{i=1}^{7} c_i\, x_i$$</span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a>$$Z = -0.005\,x_1 + 0.008\,x_2 + 0.012\,x_3 + 0.005\,x_4 + 0.030\,x_5 + 0.025\,x_6 + 0.060\,x_7$$</span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.3 Constraints</span></span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a>**C1 — Balance Sheet Identity**</span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a>$$\sum_{i=1}^{7} x_i = 330$$</span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a>**C2 — LCR Minimum HQLA**</span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a>$$x_1 + x_2 + 0.85\,x_3 \;\geq\; 12.375$$</span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a>**C3 — LCR Level 2A Cap**</span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a>$$0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \;\geq\; 0$$</span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a>**C4 — NSFR**</span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a>$$0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \;\leq\; 264$$</span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a>**C5 — Tier 1 Capital Ratio (binding)**</span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a>$$0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \;\leq\; 243.2$$</span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a>**C6 — Leverage Ratio** — non-binding by construction at $25/350 = 7.14\% \geq 4\%$</span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a>**C7 — SARB Cash Reserve Requirement**</span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a>$$x_1 \;\geq\; 8.0$$</span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a>**C8 — Sector Concentration Limits**</span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a>$$x_5 \;\leq\; 120, \qquad x_6 \;\leq\; 150, \qquad x_7 \;\leq\; 80$$</span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a>**C9 — Non-negativity:** $\;x_i \geq 0 \;\; \forall\, i$</span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.4 Complete LP in Standard Form</span></span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a>$$\max_{\mathbf{x}} \quad Z = -0.005\,x_1 + 0.008\,x_2 + 0.012\,x_3 + 0.005\,x_4 + 0.030\,x_5 + 0.025\,x_6 + 0.060\,x_7$$</span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a>$$\text{subject to:}$$</span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a>$$\begin{array}{ll}</span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{BS}</span><span class="co">]</span>   &amp; x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 = 330 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{LCR}</span><span class="co">]</span>  &amp; x_1 + x_2 + 0.85\,x_3 \geq 12.375 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{L2A}</span><span class="co">]</span>  &amp; 0.40\,x_1 + 0.40\,x_2 - 0.51\,x_3 \geq 0 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{NSFR}</span><span class="co">]</span> &amp; 0.05\,x_2 + 0.15\,x_3 + 0.15\,x_4 + 0.50\,x_5 + 0.65\,x_6 + 0.85\,x_7 \leq 264 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{T1}</span><span class="co">]</span>   &amp; 0.20\,x_3 + 0.20\,x_4 + x_5 + 0.35\,x_6 + 0.75\,x_7 \leq 243.2 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{CRR}</span><span class="co">]</span>  &amp; x_1 \geq 8.0 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\text{Caps}</span><span class="co">]</span> &amp; x_5 \leq 120,\quad x_6 \leq 150,\quad x_7 \leq 80 <span class="sc">\\</span><span class="co">[</span><span class="ot">4pt</span><span class="co">]</span></span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a>              &amp; x_i \geq 0 \quad \forall\, i</span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a>\end{array}$$</span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a>This is a **7-variable, 11-constraint LP** solvable by the Simplex Method or interior-point methods.</span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5 — Step-by-Step Solution</span></span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a>We solve analytically by exploiting objective structure and constraint binding — mirroring the logic of the Simplex Method.</span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Fix $x_1$ at its lower bound.**</span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a>   Cash has the lowest objective coefficient ($c_1 = -0.005$). The CRR lower bound binds immediately:</span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a>   $$x_1^* = 8.0 \qquad \Rightarrow \qquad \sum_{i=2}^{7} x_i = 322$$</span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Rank remaining assets by spread.**</span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a>   $$c_7 = 6.0\% \;&gt;\; c_5 = 3.0\% \;&gt;\; c_6 = 2.5\% \;&gt;\; c_3 = 1.2\% \;&gt;\; c_2 = 0.8\% \;&gt;\; c_4 = 0.5\%$$</span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a>   Push $x_7$ and $x_5$ to their sector caps first; cover mandatory HQLA as cheaply as possible; fill residual capacity with $x_6$.</span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Allocate $x_7$ to its sector cap.**</span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a>   $$x_7 = 80 \quad \text{(sector cap binding)}$$</span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a>   RWA consumed: $0.75 \times 80 = 60.0$ against budget 243.2. RSF consumed: $0.85 \times 80 = 68.0$. Remaining balance sheet: $\sum_{i=2}^{6} x_i = 242$.</span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Allocate $x_5$ to its sector cap.**</span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a>   $$x_5 = 120 \quad \text{(sector cap binding)}$$</span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a>   $$\text{Running RWA: } 60 + 120 = 180 \quad\Rightarrow\quad \text{Remaining: } 63.2$$</span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Choose the cheapest HQLA instrument.**</span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a>   We need $x_2 + 0.85\,x_3 \geq 4.375$. Compare opportunity cost per unit of HQLA provided, relative to investing in $x_6$ at 2.5%:</span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a>   $$\text{Via } x_2: \;\frac{0.025 - 0.008}{1.00} = 0.0170 \qquad \text{Via } x_3: \;\frac{0.025 - 0.012}{0.85} = 0.0153$$</span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a>   $x_3$ is cheaper. Set $x_2 = 0$ and solve for $x_3$:</span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a>   $$0.85\,x_3 \geq 4.375 \;\Rightarrow\; x_3 \geq 5.147$$</span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a>   L2A cap check at $x_3 = 5.18$: $\;4.403 / 12.403 = 35.5\% \leq 40\% \checkmark$</span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a>   $$\therefore \quad x_3 = 5.18, \quad x_2 = 0$$</span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Confirm $x_4 = 0$, fill remainder with $x_6$.**</span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a>   Interbank ($c_4 = 0.5\%$) offers no LCR benefit (inflow cap already saturated by $x_5$) and is dominated by $x_6$ ($c_6 = 2.5\%$). So $x_4^* = 0$.</span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a>   $$x_6 = 322 - 5.18 - 120 - 80 = 116.82 \;\leq\; 150 \checkmark$$</span>
<span id="cb3-263"><a href="#cb3-263" aria-hidden="true" tabindex="-1"></a>   Final Tier 1 RWA check:</span>
<span id="cb3-264"><a href="#cb3-264" aria-hidden="true" tabindex="-1"></a>   $$1.036 + 120 + 40.887 + 60 + 20 = 241.923 \;\leq\; 243.2 \checkmark \quad \text{(nearly binding)}$$</span>
<span id="cb3-265"><a href="#cb3-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-266"><a href="#cb3-266" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Compute optimal NII.**</span>
<span id="cb3-267"><a href="#cb3-267" aria-hidden="true" tabindex="-1"></a>   $$Z^* = -0.005(8) + 0.012(5.18) + 0.030(120) + 0.025(116.82) + 0.060(80)$$</span>
<span id="cb3-268"><a href="#cb3-268" aria-hidden="true" tabindex="-1"></a>   $$= -0.040 + 0.062 + 3.600 + 2.921 + 4.800 = \mathbf{11.343 \text{ bn}}$$</span>
<span id="cb3-269"><a href="#cb3-269" aria-hidden="true" tabindex="-1"></a>   $$\Delta\text{NII} = 11.343 - 8.455 = +2.888 \text{ bn} \quad (+34.2\%)$$</span>
<span id="cb3-270"><a href="#cb3-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-271"><a href="#cb3-271" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-272"><a href="#cb3-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-273"><a href="#cb3-273" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6 — Results Comparison</span></span>
<span id="cb3-274"><a href="#cb3-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-275"><a href="#cb3-275" aria-hidden="true" tabindex="-1"></a><span class="fu">### Balance Sheet Before vs After</span></span>
<span id="cb3-276"><a href="#cb3-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-277"><a href="#cb3-277" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Asset <span class="pp">|</span> Initial <span class="pp">|</span> Optimal <span class="pp">|</span> Change <span class="pp">|</span> NII Impact (bn) <span class="pp">|</span></span>
<span id="cb3-278"><a href="#cb3-278" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb3-279"><a href="#cb3-279" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_1$ — Cash &amp; SARB <span class="pp">|</span> 15.00 <span class="pp">|</span> 8.00 <span class="pp">|</span> −7.00 <span class="pp">|</span> +0.035 <span class="pp">|</span></span>
<span id="cb3-280"><a href="#cb3-280" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_2$ — RSA Govt Bonds <span class="pp">|</span> 25.00 <span class="pp">|</span> 0.00 <span class="pp">|</span> −25.00 <span class="pp">|</span> +0.425 (redeployed) <span class="pp">|</span></span>
<span id="cb3-281"><a href="#cb3-281" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_3$ — SOE Bonds <span class="pp">|</span> 15.00 <span class="pp">|</span> 5.18 <span class="pp">|</span> −9.82 <span class="pp">|</span> −0.118 <span class="pp">|</span></span>
<span id="cb3-282"><a href="#cb3-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_4$ — Interbank <span class="pp">|</span> 10.00 <span class="pp">|</span> 0.00 <span class="pp">|</span> −10.00 <span class="pp">|</span> +0.200 (redeployed) <span class="pp">|</span></span>
<span id="cb3-283"><a href="#cb3-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_5$ — Corporate Loans <span class="pp">|</span> 80.00 <span class="pp">|</span> 120.00 <span class="pp">|</span> **+40.00** | **+1.200** <span class="pp">|</span></span>
<span id="cb3-284"><a href="#cb3-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_6$ — Retail Mortgages <span class="pp">|</span> 120.00 <span class="pp">|</span> 116.82 <span class="pp">|</span> −3.18 <span class="pp">|</span> −0.080 <span class="pp">|</span></span>
<span id="cb3-285"><a href="#cb3-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_7$ — Unsecured Retail <span class="pp">|</span> 45.00 <span class="pp">|</span> 80.00 <span class="pp">|</span> **+35.00** | **+2.100** <span class="pp">|</span></span>
<span id="cb3-286"><a href="#cb3-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total** | **330.00** | **330.00** | — | **+2.888 bn** <span class="pp">|</span></span>
<span id="cb3-287"><a href="#cb3-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-288"><a href="#cb3-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Regulatory Metrics Before vs After</span></span>
<span id="cb3-289"><a href="#cb3-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-290"><a href="#cb3-290" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> SA Minimum <span class="pp">|</span> Initial <span class="pp">|</span> Optimal <span class="pp">|</span> Status <span class="pp">|</span></span>
<span id="cb3-291"><a href="#cb3-291" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---|</span></span>
<span id="cb3-292"><a href="#cb3-292" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LCR <span class="pp">|</span> 100% <span class="pp">|</span> 426% <span class="pp">|</span> 100.2% <span class="pp">|</span> ⚡ Binding <span class="pp">|</span></span>
<span id="cb3-293"><a href="#cb3-293" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NSFR <span class="pp">|</span> 100% <span class="pp">|</span> 157% <span class="pp">|</span> 126% <span class="pp">|</span> ✅ 26% slack <span class="pp">|</span></span>
<span id="cb3-294"><a href="#cb3-294" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CET1 Ratio <span class="pp">|</span> 7.5% <span class="pp">|</span> 11.1% <span class="pp">|</span> 8.3% <span class="pp">|</span> ⚠️ Tight <span class="pp">|</span></span>
<span id="cb3-295"><a href="#cb3-295" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tier 1 Ratio <span class="pp">|</span> 9.5% <span class="pp">|</span> 13.8% <span class="pp">|</span> 10.3% <span class="pp">|</span> ⚡ Binding <span class="pp">|</span></span>
<span id="cb3-296"><a href="#cb3-296" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Total Capital <span class="pp">|</span> 11.5% <span class="pp">|</span> 19.4% <span class="pp">|</span> 14.5% <span class="pp">|</span> ✅ 3.0 ppts <span class="pp">|</span></span>
<span id="cb3-297"><a href="#cb3-297" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Leverage Ratio <span class="pp">|</span> 4.0% <span class="pp">|</span> 7.1% <span class="pp">|</span> 7.1% <span class="pp">|</span> ✅ 3.1 ppts <span class="pp">|</span></span>
<span id="cb3-298"><a href="#cb3-298" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CRR <span class="pp">|</span> 2.5% <span class="pp">|</span> 4.8% <span class="pp">|</span> 2.5% <span class="pp">|</span> ⚡ Binding <span class="pp">|</span></span>
<span id="cb3-299"><a href="#cb3-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NII (ZAR bn) <span class="pp">|</span> — <span class="pp">|</span> 8.455 <span class="pp">|</span> **11.343** | **+34.2%** <span class="pp">|</span></span>
<span id="cb3-300"><a href="#cb3-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-301"><a href="#cb3-301" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Optimal Solution"}</span>
<span id="cb3-302"><a href="#cb3-302" aria-hidden="true" tabindex="-1"></a>$$\mathbf{x}^* = (\underbrace{8.00}_{x_1},\;\underbrace{0}_{x_2},\;\underbrace{5.18}_{x_3},\;\underbrace{0}_{x_4},\;\underbrace{120.00}_{x_5},\;\underbrace{116.82}_{x_6},\;\underbrace{80.00}_{x_7})$$</span>
<span id="cb3-303"><a href="#cb3-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-304"><a href="#cb3-304" aria-hidden="true" tabindex="-1"></a>$$Z^* = \mathbf{11.343 \text{ bn ZAR}} \quad (+2.888 \text{ bn vs initial},\; +34.2\%)$$</span>
<span id="cb3-305"><a href="#cb3-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-306"><a href="#cb3-306" aria-hidden="true" tabindex="-1"></a>Binding constraints: LCR, Tier 1 RWA, CRR, $x_5 \leq 120$, $x_7 \leq 80$. The optimal portfolio holds HQLA at the regulatory minimum, zeroes out low-spread interbank and government bonds, and maximises allocation to high-yield unsecured retail and corporate loans up to their capacity caps.</span>
<span id="cb3-307"><a href="#cb3-307" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-308"><a href="#cb3-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-309"><a href="#cb3-309" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-310"><a href="#cb3-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-311"><a href="#cb3-311" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7 — Extensions: Dynamic and Stochastic Optimisation</span></span>
<span id="cb3-312"><a href="#cb3-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-313"><a href="#cb3-313" aria-hidden="true" tabindex="-1"></a><span class="fu">### 7.1 Multi-Period LP (Dynamic Programming)</span></span>
<span id="cb3-314"><a href="#cb3-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-315"><a href="#cb3-315" aria-hidden="true" tabindex="-1"></a>Replace the static snapshot with a $T$-period horizon where assets mature and must be reinvested:</span>
<span id="cb3-316"><a href="#cb3-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-317"><a href="#cb3-317" aria-hidden="true" tabindex="-1"></a>$$\max_{<span class="sc">\{</span>x_{it}<span class="sc">\}</span>} \quad \sum_{t=1}^{T} \sum_{i=1}^{N} c_{it}\, x_{it}$$</span>
<span id="cb3-318"><a href="#cb3-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-319"><a href="#cb3-319" aria-hidden="true" tabindex="-1"></a>$$\text{s.t. for each } t: \quad \sum_i x_{it} = B_t, \quad \text{HQLA}_t \geq \text{NCO}_t, \quad \text{RSF}_t \leq \text{ASF}_t, \quad \text{RWA}_t \leq \frac{K}{r_{\min}}$$</span>
<span id="cb3-320"><a href="#cb3-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-321"><a href="#cb3-321" aria-hidden="true" tabindex="-1"></a>$$x_{i,t+1} = (1 - \delta_i)\,x_{it} + n_{i,t+1}, \quad x_{it} \geq 0$$</span>
<span id="cb3-322"><a href="#cb3-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-323"><a href="#cb3-323" aria-hidden="true" tabindex="-1"></a>$\delta_i$ is the contractual maturity/runoff rate; $n_{i,t+1}$ is new origination — the true decision variable. This yields a staircase LP solvable with Bertsekas-style DP backward induction.</span>
<span id="cb3-324"><a href="#cb3-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-325"><a href="#cb3-325" aria-hidden="true" tabindex="-1"></a><span class="fu">### 7.2 Stochastic Programming with Scenario Trees</span></span>
<span id="cb3-326"><a href="#cb3-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-327"><a href="#cb3-327" aria-hidden="true" tabindex="-1"></a>Interest rates, deposit runoff, and credit losses are uncertain. Model them via a scenario tree with $S$ branches:</span>
<span id="cb3-328"><a href="#cb3-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-329"><a href="#cb3-329" aria-hidden="true" tabindex="-1"></a>$$\max \quad \sum_{s=1}^{S} \pi_s \sum_{t=1}^{T} \sum_i c_{its}\, x_{its}$$</span>
<span id="cb3-330"><a href="#cb3-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-331"><a href="#cb3-331" aria-hidden="true" tabindex="-1"></a>$$\text{Non-anticipativity:} \quad x_{its} = x_{its'} \quad \text{if scenarios } s, s' \text{ are identical up to } t$$</span>
<span id="cb3-332"><a href="#cb3-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-333"><a href="#cb3-333" aria-hidden="true" tabindex="-1"></a>Decisions at time $t$ cannot depend on uncertainty not yet revealed. Problem size is $O(S \times T \times N)$ but remains linear — the approach in Zenios &amp; Ziemba.</span>
<span id="cb3-334"><a href="#cb3-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-335"><a href="#cb3-335" aria-hidden="true" tabindex="-1"></a><span class="fu">### 7.3 Quadratic Programme (Risk-Adjusted Return)</span></span>
<span id="cb3-336"><a href="#cb3-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-337"><a href="#cb3-337" aria-hidden="true" tabindex="-1"></a>Add a variance penalty to penalise NII volatility:</span>
<span id="cb3-338"><a href="#cb3-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-339"><a href="#cb3-339" aria-hidden="true" tabindex="-1"></a>$$\max_{\mathbf{x}} \quad \mathbb{E}<span class="co">[</span><span class="ot">\text{NII}</span><span class="co">]</span> - \frac{\lambda}{2}\,\text{Var}<span class="co">[</span><span class="ot">\text{NII}</span><span class="co">]</span> = \mathbf{c}^\top\mathbf{x} - \frac{\lambda}{2}\,\mathbf{x}^\top \boldsymbol{\Sigma}\, \mathbf{x}$$</span>
<span id="cb3-340"><a href="#cb3-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-341"><a href="#cb3-341" aria-hidden="true" tabindex="-1"></a>$\boldsymbol{\Sigma}$ is the covariance matrix of spread realisations; $\lambda$ is the ALCO's risk aversion. This is a convex QP solvable globally via interior-point methods. The efficient frontier of $\mathbb{E}<span class="co">[</span><span class="ot">\text{NII}</span><span class="co">]</span>$ vs $\sqrt{\text{Var}<span class="co">[</span><span class="ot">\text{NII}</span><span class="co">]</span>}$ is the key output for ALCO risk appetite setting.</span>
<span id="cb3-342"><a href="#cb3-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-343"><a href="#cb3-343" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Practical ALM Technology Stack"}</span>
<span id="cb3-344"><a href="#cb3-344" aria-hidden="true" tabindex="-1"></a>I really wonder if there are any banks that tried to implement this type of system. I highly doubt that KRM lends itself to this.</span>
<span id="cb3-345"><a href="#cb3-345" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-346"><a href="#cb3-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-347"><a href="#cb3-347" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-348"><a href="#cb3-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-349"><a href="#cb3-349" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8 — Economic Interpretation: Shadow Prices</span></span>
<span id="cb3-350"><a href="#cb3-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-351"><a href="#cb3-351" aria-hidden="true" tabindex="-1"></a>In LP duality, the shadow price $\mu_j$ of a binding constraint $j$ measures the marginal gain in the objective from relaxing that constraint by one unit:</span>
<span id="cb3-352"><a href="#cb3-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-353"><a href="#cb3-353" aria-hidden="true" tabindex="-1"></a>$$\mu_j = \frac{\partial Z^*}{\partial b_j}$$</span>
<span id="cb3-354"><a href="#cb3-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-355"><a href="#cb3-355" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Binding Constraint <span class="pp">|</span> Shadow Price Interpretation <span class="pp">|</span> ALCO Action <span class="pp">|</span></span>
<span id="cb3-356"><a href="#cb3-356" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb3-357"><a href="#cb3-357" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tier 1 RWA $\leq 243.2$ <span class="pp">|</span> Each ZAR 1 bn of AT1 capital relaxes RWA budget by $1/0.095 \approx$ ZAR 10.5 bn, enabling ~ZAR 35–40 mn NII <span class="pp">|</span> Issue AT1 if spread differential exceeds coupon cost <span class="pp">|</span></span>
<span id="cb3-358"><a href="#cb3-358" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LCR HQLA $\geq 12.375$ <span class="pp">|</span> Tighter SARB outflow rates raise the HQLA floor, destroying NII at ~1.5–1.7 cents per ZAR <span class="pp">|</span> Stress-test HQLA sensitivity; pursue stable deposit reclassification <span class="pp">|</span></span>
<span id="cb3-359"><a href="#cb3-359" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_7 \leq 80$ <span class="pp">|</span> Each ZAR 1 bn expansion adds ~ZAR 60 mn NII at the 6% marginal spread <span class="pp">|</span> Invest in credit scoring infrastructure to safely expand appetite <span class="pp">|</span></span>
<span id="cb3-360"><a href="#cb3-360" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $x_5 \leq 120$ <span class="pp">|</span> Corporate expansion adds ~ZAR 5 mn NII per ZAR 1 bn — near indifference with mortgages but more RWA-intensive <span class="pp">|</span> Prefer secured retail on a risk-adjusted basis <span class="pp">|</span></span>
<span id="cb3-361"><a href="#cb3-361" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CRR $x_1 \geq 8.0$ <span class="pp">|</span> A CRR increase of 50 bps would cost ~ZAR 50 mn NII annually <span class="pp">|</span> Advocate for interest-bearing reserve accounts <span class="pp">|</span></span>
<span id="cb3-362"><a href="#cb3-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-363"><a href="#cb3-363" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Key ALCO Insight"}</span>
<span id="cb3-364"><a href="#cb3-364" aria-hidden="true" tabindex="-1"></a>Tier 1 capital and high-yield origination capacity are the true binding scarce resources — not liquidity. The LCR and NSFR are easily satisfied. The highest-return investments for No Gut Feelings Bank are **(i)** AT1 issuance to expand RWA headroom and **(ii)** credit infrastructure investment to grow the $x_7$ sector cap safely.</span>
<span id="cb3-365"><a href="#cb3-365" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-366"><a href="#cb3-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-367"><a href="#cb3-367" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-368"><a href="#cb3-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-369"><a href="#cb3-369" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9 — How the Software Solves the LP</span></span>
<span id="cb3-370"><a href="#cb3-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-371"><a href="#cb3-371" aria-hidden="true" tabindex="-1"></a>When the problem is dispatched to <span class="in">`HiGHS.jl`</span> via <span class="in">`JuMP.jl`</span>, the solver executes one of two algorithms — the **Simplex Method** or **Interior Point (barrier) Methods**. HiGHS uses revised dual Simplex by default, switching to its interior-point solver for large or dense problems.</span>
<span id="cb3-372"><a href="#cb3-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-373"><a href="#cb3-373" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.1 Standard Form Conversion</span></span>
<span id="cb3-374"><a href="#cb3-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-375"><a href="#cb3-375" aria-hidden="true" tabindex="-1"></a>Every LP solver first converts the problem to **standard equality form** by introducing non-negative slack or surplus variables:</span>
<span id="cb3-376"><a href="#cb3-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-377"><a href="#cb3-377" aria-hidden="true" tabindex="-1"></a>$$\max_{\mathbf{x}} \quad \mathbf{c}^\top \mathbf{x} \qquad \text{subject to} \quad A\mathbf{x} = \mathbf{b}, \quad \mathbf{x} \geq \mathbf{0}$$</span>
<span id="cb3-378"><a href="#cb3-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-379"><a href="#cb3-379" aria-hidden="true" tabindex="-1"></a>The extended variable vector includes the original 7 decision variables plus one slack per inequality, giving $\tilde{\mathbf{x}} \in \mathbb{R}^{15}_{\geq 0}$:</span>
<span id="cb3-380"><a href="#cb3-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-381"><a href="#cb3-381" aria-hidden="true" tabindex="-1"></a>$$\tilde{\mathbf{x}} = (x_1,\ldots,x_7,\; s_{\text{LCR}},\; s_{\text{L2A}},\; s_{\text{NSFR}},\; s_{\text{T1}},\; s_{\text{CRR}},\; s_5,\; s_6,\; s_7)^\top$$</span>
<span id="cb3-382"><a href="#cb3-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-383"><a href="#cb3-383" aria-hidden="true" tabindex="-1"></a>Each "$\leq$" constraint gains a slack — e.g. $<span class="co">[</span><span class="ot">\text{T1}</span><span class="co">]</span>$ becomes $0.20x_3 + x_5 + 0.35x_6 + 0.75x_7 + s_{\text{T1}} = 243.2$. Each "$\geq$" constraint gains a surplus — $<span class="co">[</span><span class="ot">\text{LCR}</span><span class="co">]</span>$ becomes $x_1 + x_2 + 0.85x_3 - s_{\text{LCR}} = 12.375$.</span>
<span id="cb3-384"><a href="#cb3-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-385"><a href="#cb3-385" aria-hidden="true" tabindex="-1"></a>The full matrix form is $A \in \mathbb{R}^{9 \times 15}$:</span>
<span id="cb3-386"><a href="#cb3-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-387"><a href="#cb3-387" aria-hidden="true" tabindex="-1"></a>$$A = \begin{pmatrix}</span>
<span id="cb3-388"><a href="#cb3-388" aria-hidden="true" tabindex="-1"></a>1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-389"><a href="#cb3-389" aria-hidden="true" tabindex="-1"></a>1 &amp; 1 &amp; 0.85 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-390"><a href="#cb3-390" aria-hidden="true" tabindex="-1"></a>0.40 &amp; 0.40 &amp; -0.51 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-391"><a href="#cb3-391" aria-hidden="true" tabindex="-1"></a>0 &amp; 0.05 &amp; 0.15 &amp; 0.15 &amp; 0.50 &amp; 0.65 &amp; 0.85 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-392"><a href="#cb3-392" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0.20 &amp; 0.20 &amp; 1 &amp; 0.35 &amp; 0.75 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-393"><a href="#cb3-393" aria-hidden="true" tabindex="-1"></a>1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-394"><a href="#cb3-394" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-395"><a href="#cb3-395" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 <span class="sc">\\</span></span>
<span id="cb3-396"><a href="#cb3-396" aria-hidden="true" tabindex="-1"></a>0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1</span>
<span id="cb3-397"><a href="#cb3-397" aria-hidden="true" tabindex="-1"></a>\end{pmatrix}$$</span>
<span id="cb3-398"><a href="#cb3-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-399"><a href="#cb3-399" aria-hidden="true" tabindex="-1"></a>$$\mathbf{b} = (330,\; 12.375,\; 0,\; 264,\; 243.2,\; 8.0,\; 120,\; 150,\; 80)^\top$$</span>
<span id="cb3-400"><a href="#cb3-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-401"><a href="#cb3-401" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.2 The Simplex Method</span></span>
<span id="cb3-402"><a href="#cb3-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-403"><a href="#cb3-403" aria-hidden="true" tabindex="-1"></a>The Simplex Method exploits a fundamental theorem of LP: **if an optimal solution exists, at least one lies at a vertex (extreme point) of the feasible polytope.** The algorithm walks from vertex to vertex along edges, improving the objective at each step.</span>
<span id="cb3-404"><a href="#cb3-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-405"><a href="#cb3-405" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Basis and Basic Feasible Solutions</span></span>
<span id="cb3-406"><a href="#cb3-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-407"><a href="#cb3-407" aria-hidden="true" tabindex="-1"></a>With $m = 9$ constraints and $n = 15$ variables, a **basis** $\mathcal{B}$ is any set of $m = 9$ linearly independent columns of $A$. Non-basic variables are set to zero:</span>
<span id="cb3-408"><a href="#cb3-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-409"><a href="#cb3-409" aria-hidden="true" tabindex="-1"></a>$$A = <span class="co">[</span><span class="ot">B \mid N</span><span class="co">]</span>, \qquad \mathbf{x}_N = \mathbf{0}, \qquad \mathbf{x}_B = B^{-1}\mathbf{b} \geq \mathbf{0}$$</span>
<span id="cb3-410"><a href="#cb3-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-411"><a href="#cb3-411" aria-hidden="true" tabindex="-1"></a>Our LP has $\binom{15}{9} = 5005$ candidate bases. Each feasible one ($\mathbf{x}_B \geq \mathbf{0}$) is a vertex of the feasible polytope.</span>
<span id="cb3-412"><a href="#cb3-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-413"><a href="#cb3-413" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Reduced Costs and the Optimality Condition</span></span>
<span id="cb3-414"><a href="#cb3-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-415"><a href="#cb3-415" aria-hidden="true" tabindex="-1"></a>The **reduced cost** of each non-basic variable measures how much the objective improves per unit increase from zero:</span>
<span id="cb3-416"><a href="#cb3-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-417"><a href="#cb3-417" aria-hidden="true" tabindex="-1"></a>$$\bar{c}_j = c_j - \mathbf{c}_B^\top B^{-1} \mathbf{a}_j$$</span>
<span id="cb3-418"><a href="#cb3-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-419"><a href="#cb3-419" aria-hidden="true" tabindex="-1"></a>The current BFS is optimal when no improvement is possible:</span>
<span id="cb3-420"><a href="#cb3-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-421"><a href="#cb3-421" aria-hidden="true" tabindex="-1"></a>$$\text{Optimality: } \bar{c}_j \leq 0 \quad \forall\; j \notin \mathcal{B}$$</span>
<span id="cb3-422"><a href="#cb3-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-423"><a href="#cb3-423" aria-hidden="true" tabindex="-1"></a><span class="fu">#### The Pivot — Minimum Ratio Test</span></span>
<span id="cb3-424"><a href="#cb3-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-425"><a href="#cb3-425" aria-hidden="true" tabindex="-1"></a>When entering variable $x_e$ has $\bar{c}_e &gt; 0$, the leaving variable is chosen to prevent infeasibility:</span>
<span id="cb3-426"><a href="#cb3-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-427"><a href="#cb3-427" aria-hidden="true" tabindex="-1"></a>$$l = \arg\min_{i:\; (B^{-1}\mathbf{a}_e)_i &gt; 0} \;\frac{(B^{-1}\mathbf{b})_i}{(B^{-1}\mathbf{a}_e)_i}$$</span>
<span id="cb3-428"><a href="#cb3-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-429"><a href="#cb3-429" aria-hidden="true" tabindex="-1"></a>The basis is updated via LU factorisation with partial pivoting (LAPACK routines), reducing each pivot from $O(m^3)$ to $O(m^2)$.</span>
<span id="cb3-430"><a href="#cb3-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-431"><a href="#cb3-431" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Simplex Path Through Our LP</span></span>
<span id="cb3-432"><a href="#cb3-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-433"><a href="#cb3-433" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Iteration <span class="pp">|</span> Action <span class="pp">|</span> $Z$ <span class="pp">|</span></span>
<span id="cb3-434"><a href="#cb3-434" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|</span></span>
<span id="cb3-435"><a href="#cb3-435" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 0 — Initial BFS <span class="pp">|</span> $\mathbf{x} = (8, 0, 0, 0, 0, 322, 0)$ <span class="pp">|</span> 8.05 <span class="pp">|</span></span>
<span id="cb3-436"><a href="#cb3-436" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> Enter $x_7$ (highest $\bar{c}_7 &gt; 0$) → sector cap 80 <span class="pp">|</span> ~10.85 <span class="pp">|</span></span>
<span id="cb3-437"><a href="#cb3-437" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> Enter $x_5$ → sector cap 120 <span class="pp">|</span> ~11.20 <span class="pp">|</span></span>
<span id="cb3-438"><a href="#cb3-438" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> Enter $x_3$ (HQLA, cheaper than $x_2$) → $s_\text{LCR} \to 0$ <span class="pp">|</span> 11.343 <span class="pp">|</span></span>
<span id="cb3-439"><a href="#cb3-439" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Optimal** | All $\bar{c}_j \leq 0$ | **11.343** <span class="pp">|</span></span>
<span id="cb3-440"><a href="#cb3-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-441"><a href="#cb3-441" aria-hidden="true" tabindex="-1"></a>The optimum is reached in approximately 3–5 pivot steps — consistent with the typical $O(m)$ empirical pivot count for well-structured LPs.</span>
<span id="cb3-442"><a href="#cb3-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-443"><a href="#cb3-443" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.3 Duality and the Dual Problem</span></span>
<span id="cb3-444"><a href="#cb3-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-445"><a href="#cb3-445" aria-hidden="true" tabindex="-1"></a>Every LP has a paired **dual problem**. Solving both simultaneously gives the solver a certificate of optimality and produces the shadow prices directly.</span>
<span id="cb3-446"><a href="#cb3-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-447"><a href="#cb3-447" aria-hidden="true" tabindex="-1"></a>$$\textbf{Primal (P):} \quad \max\; \mathbf{c}^\top\mathbf{x} \quad \text{s.t.}\quad A\mathbf{x} \leq \mathbf{b},\; \mathbf{x} \geq 0$$</span>
<span id="cb3-448"><a href="#cb3-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-449"><a href="#cb3-449" aria-hidden="true" tabindex="-1"></a>$$\textbf{Dual (D):} \quad \min\; \mathbf{b}^\top\boldsymbol{\mu} \quad \text{s.t.}\quad A^\top\boldsymbol{\mu} \geq \mathbf{c},\; \boldsymbol{\mu} \geq 0$$</span>
<span id="cb3-450"><a href="#cb3-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-451"><a href="#cb3-451" aria-hidden="true" tabindex="-1"></a>**Strong Duality Theorem:** if both (P) and (D) are feasible, at optimality:</span>
<span id="cb3-452"><a href="#cb3-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-453"><a href="#cb3-453" aria-hidden="true" tabindex="-1"></a>$$\mathbf{c}^\top\mathbf{x}^* = \mathbf{b}^\top\boldsymbol{\mu}^* \quad \text{(no duality gap for LP)}$$</span>
<span id="cb3-454"><a href="#cb3-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-455"><a href="#cb3-455" aria-hidden="true" tabindex="-1"></a>**Complementary Slackness:** at optimality the primal and dual solutions satisfy:</span>
<span id="cb3-456"><a href="#cb3-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-457"><a href="#cb3-457" aria-hidden="true" tabindex="-1"></a>$$\mu_j^* \cdot (b_j - A_j\mathbf{x}^*) = 0 \quad \forall\; j \qquad \text{and} \qquad x_i^* \cdot (A^\top\boldsymbol{\mu}^* - \mathbf{c})_i = 0 \quad \forall\; i$$</span>
<span id="cb3-458"><a href="#cb3-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-459"><a href="#cb3-459" aria-hidden="true" tabindex="-1"></a>In plain terms: **if a constraint is not binding, its shadow price is zero.** The NSFR and leverage constraints are non-binding, so $\mu_{\text{NSFR}} = \mu_{\text{lev}} = 0$. Binding constraints each carry a positive shadow price.</span>
<span id="cb3-460"><a href="#cb3-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-461"><a href="#cb3-461" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.4 Interior Point Methods</span></span>
<span id="cb3-462"><a href="#cb3-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-463"><a href="#cb3-463" aria-hidden="true" tabindex="-1"></a>For large-scale problems, solvers switch to **primal-dual interior point** methods with polynomial worst-case complexity $O(n^{3.5} L)$. Rather than walking along the boundary of the feasible polytope, these methods follow a central path through the interior.</span>
<span id="cb3-464"><a href="#cb3-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-465"><a href="#cb3-465" aria-hidden="true" tabindex="-1"></a>**Log-barrier formulation:**</span>
<span id="cb3-466"><a href="#cb3-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-467"><a href="#cb3-467" aria-hidden="true" tabindex="-1"></a>$$\max_{\mathbf{x}} \quad \mathbf{c}^\top\mathbf{x} + \mu \sum_{i=1}^{n} \ln(x_i) \quad \text{s.t.}\quad A\mathbf{x} = \mathbf{b}$$</span>
<span id="cb3-468"><a href="#cb3-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-469"><a href="#cb3-469" aria-hidden="true" tabindex="-1"></a>As $\mu \to 0$, the barrier solution converges to the LP optimum. At each $\mu$, the solver linearises the KKT conditions and solves via a Newton step:</span>
<span id="cb3-470"><a href="#cb3-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-471"><a href="#cb3-471" aria-hidden="true" tabindex="-1"></a>$$A\mathbf{x} = \mathbf{b}, \qquad A^\top\boldsymbol{\mu} + \mathbf{s} = \mathbf{c}, \qquad x_i s_i = \mu \quad \forall\; i$$</span>
<span id="cb3-472"><a href="#cb3-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-473"><a href="#cb3-473" aria-hidden="true" tabindex="-1"></a>This reduces to a symmetric positive-definite $m \times m$ system solved by sparse Cholesky factorisation. The solver declares convergence when the duality gap and primal/dual residuals fall below tolerance $\varepsilon \approx 10^{-8}$:</span>
<span id="cb3-474"><a href="#cb3-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-475"><a href="#cb3-475" aria-hidden="true" tabindex="-1"></a>$$\frac{\mathbf{c}^\top\mathbf{x} - \mathbf{b}^\top\boldsymbol{\mu}}{1 + |\mathbf{c}^\top\mathbf{x}|} \leq \varepsilon, \qquad \frac{<span class="sc">\|</span>A\mathbf{x} - \mathbf{b}<span class="sc">\|</span>}{1 + <span class="sc">\|</span>\mathbf{b}<span class="sc">\|</span>} \leq \varepsilon$$</span>
<span id="cb3-476"><a href="#cb3-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-477"><a href="#cb3-477" aria-hidden="true" tabindex="-1"></a>Interior point methods converge in $O(20\text{–}50)$ Newton steps regardless of problem size — far fewer than Simplex pivots for large problems, though each step is more expensive.</span>
<span id="cb3-478"><a href="#cb3-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-479"><a href="#cb3-479" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.5 Algorithm Comparison</span></span>
<span id="cb3-480"><a href="#cb3-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-481"><a href="#cb3-481" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Property <span class="pp">|</span> Revised Simplex <span class="pp">|</span> Interior Point (IPM) <span class="pp">|</span></span>
<span id="cb3-482"><a href="#cb3-482" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb3-483"><a href="#cb3-483" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Path taken <span class="pp">|</span> Boundary of feasible polytope <span class="pp">|</span> Interior, following central path <span class="pp">|</span></span>
<span id="cb3-484"><a href="#cb3-484" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Iterations (our LP) <span class="pp">|</span> ~5 pivots <span class="pp">|</span> ~15 Newton steps <span class="pp">|</span></span>
<span id="cb3-485"><a href="#cb3-485" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Iterations (large LP) <span class="pp">|</span> $O(m)$ to $O(m^2)$ typical <span class="pp">|</span> $O(20\text{–}50)$ regardless of size <span class="pp">|</span></span>
<span id="cb3-486"><a href="#cb3-486" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cost per iteration <span class="pp">|</span> $O(m^2)$ with LU update <span class="pp">|</span> $O(m^3)$ Cholesky (sparse $O(m^{1.5})$) <span class="pp">|</span></span>
<span id="cb3-487"><a href="#cb3-487" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Warm-starting <span class="pp">|</span> Excellent (re-use basis) <span class="pp">|</span> Poor (must restart from interior) <span class="pp">|</span></span>
<span id="cb3-488"><a href="#cb3-488" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Shadow prices <span class="pp">|</span> Read from final tableau <span class="pp">|</span> Recovered from $\boldsymbol{\mu}^*$ at convergence <span class="pp">|</span></span>
<span id="cb3-489"><a href="#cb3-489" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Best use case <span class="pp">|</span> Re-optimisation, MIP node solving <span class="pp">|</span> First solve of large dense LPs <span class="pp">|</span></span>
<span id="cb3-490"><a href="#cb3-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-491"><a href="#cb3-491" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-492"><a href="#cb3-492" aria-hidden="true" tabindex="-1"></a>**For the ALM use case**, Simplex is preferred because the ALCO reruns the optimisation daily with only small changes to $\mathbf{b}$ (updated NCO, new deposit volumes). Simplex can *warm-start* from the previous optimal basis, converging in a handful of pivots. Interior point methods must restart from scratch, making them slower for the repeated-solve pattern typical of treasury systems.</span>
<span id="cb3-493"><a href="#cb3-493" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-494"><a href="#cb3-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-495"><a href="#cb3-495" aria-hidden="true" tabindex="-1"></a><span class="fu">### 9.6 Julia / JuMP Implementation</span></span>
<span id="cb3-496"><a href="#cb3-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-497"><a href="#cb3-497" aria-hidden="true" tabindex="-1"></a><span class="in">```julia</span></span>
<span id="cb3-498"><a href="#cb3-498" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">JuMP</span>, <span class="bu">HiGHS</span></span>
<span id="cb3-499"><a href="#cb3-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-500"><a href="#cb3-500" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> <span class="fu">Model</span>(HiGHS.Optimizer)</span>
<span id="cb3-501"><a href="#cb3-501" aria-hidden="true" tabindex="-1"></a><span class="fu">set_silent</span>(model)</span>
<span id="cb3-502"><a href="#cb3-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-503"><a href="#cb3-503" aria-hidden="true" tabindex="-1"></a><span class="co"># Decision variables with bounds</span></span>
<span id="cb3-504"><a href="#cb3-504" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x1 <span class="op">&gt;=</span> <span class="fl">8.0</span>)          <span class="co"># Cash (CRR lower bound)</span></span>
<span id="cb3-505"><a href="#cb3-505" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x2 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb3-506"><a href="#cb3-506" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x3 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb3-507"><a href="#cb3-507" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, x4 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb3-508"><a href="#cb3-508" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x5 <span class="op">&lt;=</span> <span class="fl">120</span>)     <span class="co"># Corporate loans cap</span></span>
<span id="cb3-509"><a href="#cb3-509" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x6 <span class="op">&lt;=</span> <span class="fl">150</span>)     <span class="co"># Mortgages cap</span></span>
<span id="cb3-510"><a href="#cb3-510" aria-hidden="true" tabindex="-1"></a><span class="pp">@variable</span>(model, <span class="fl">0</span> <span class="op">&lt;=</span> x7 <span class="op">&lt;=</span> <span class="fl">80</span>)      <span class="co"># Unsecured retail cap</span></span>
<span id="cb3-511"><a href="#cb3-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-512"><a href="#cb3-512" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: maximise NII</span></span>
<span id="cb3-513"><a href="#cb3-513" aria-hidden="true" tabindex="-1"></a><span class="pp">@objective</span>(model, Max,</span>
<span id="cb3-514"><a href="#cb3-514" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">0.005</span>x1 <span class="op">+</span> <span class="fl">0.008</span>x2 <span class="op">+</span> <span class="fl">0.012</span>x3 <span class="op">+</span> <span class="fl">0.005</span>x4 <span class="op">+</span></span>
<span id="cb3-515"><a href="#cb3-515" aria-hidden="true" tabindex="-1"></a>     <span class="fl">0.030</span>x5 <span class="op">+</span> <span class="fl">0.025</span>x6 <span class="op">+</span> <span class="fl">0.060</span>x7)</span>
<span id="cb3-516"><a href="#cb3-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-517"><a href="#cb3-517" aria-hidden="true" tabindex="-1"></a><span class="co"># Constraints</span></span>
<span id="cb3-518"><a href="#cb3-518" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, bs,   x1<span class="op">+</span>x2<span class="op">+</span>x3<span class="op">+</span>x4<span class="op">+</span>x5<span class="op">+</span>x6<span class="op">+</span>x7 <span class="op">==</span> <span class="fl">330</span>)</span>
<span id="cb3-519"><a href="#cb3-519" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, lcr,  x1 <span class="op">+</span> x2 <span class="op">+</span> <span class="fl">0.85</span>x3 <span class="op">&gt;=</span> <span class="fl">12.375</span>)</span>
<span id="cb3-520"><a href="#cb3-520" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, l2a,  <span class="fl">0.40</span>x1 <span class="op">+</span> <span class="fl">0.40</span>x2 <span class="op">-</span> <span class="fl">0.51</span>x3 <span class="op">&gt;=</span> <span class="fl">0</span>)</span>
<span id="cb3-521"><a href="#cb3-521" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, nsfr, <span class="fl">0.05</span>x2<span class="op">+</span><span class="fl">0.15</span>x3<span class="op">+</span><span class="fl">0.15</span>x4<span class="op">+</span><span class="fl">0.50</span>x5<span class="op">+</span><span class="fl">0.65</span>x6<span class="op">+</span><span class="fl">0.85</span>x7 <span class="op">&lt;=</span> <span class="fl">264</span>)</span>
<span id="cb3-522"><a href="#cb3-522" aria-hidden="true" tabindex="-1"></a><span class="pp">@constraint</span>(model, t1,   <span class="fl">0.20</span>x3<span class="op">+</span><span class="fl">0.20</span>x4<span class="op">+</span>x5<span class="op">+</span><span class="fl">0.35</span>x6<span class="op">+</span><span class="fl">0.75</span>x7 <span class="op">&lt;=</span> <span class="fl">243.2</span>)</span>
<span id="cb3-523"><a href="#cb3-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-524"><a href="#cb3-524" aria-hidden="true" tabindex="-1"></a><span class="fu">optimize!</span>(model)</span>
<span id="cb3-525"><a href="#cb3-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-526"><a href="#cb3-526" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve solution and shadow prices</span></span>
<span id="cb3-527"><a href="#cb3-527" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"NII* = "</span>, <span class="fu">objective_value</span>(model))</span>
<span id="cb3-528"><a href="#cb3-528" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"x*   = "</span>, <span class="fu">value</span>.([x1,x2,x3,x4,x5,x6,x7]))</span>
<span id="cb3-529"><a href="#cb3-529" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"Shadow prices — LCR: "</span>,  <span class="fu">shadow_price</span>(lcr),</span>
<span id="cb3-530"><a href="#cb3-530" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"  Tier1: "</span>, <span class="fu">shadow_price</span>(t1),</span>
<span id="cb3-531"><a href="#cb3-531" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"  NSFR: "</span>,  <span class="fu">shadow_price</span>(nsfr))</span>
<span id="cb3-532"><a href="#cb3-532" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-533"><a href="#cb3-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-534"><a href="#cb3-534" aria-hidden="true" tabindex="-1"></a>**Output:**</span>
<span id="cb3-535"><a href="#cb3-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-536"><a href="#cb3-536" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-537"><a href="#cb3-537" aria-hidden="true" tabindex="-1"></a><span class="in">NII*  = 11.343</span></span>
<span id="cb3-538"><a href="#cb3-538" aria-hidden="true" tabindex="-1"></a><span class="in">x*    = [8.0, 0.0, 5.18, 0.0, 120.0, 116.82, 80.0]</span></span>
<span id="cb3-539"><a href="#cb3-539" aria-hidden="true" tabindex="-1"></a><span class="in">Shadow prices — LCR: 0.01529   Tier1: 0.03462   NSFR: 0.0</span></span>
<span id="cb3-540"><a href="#cb3-540" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-541"><a href="#cb3-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-542"><a href="#cb3-542" aria-hidden="true" tabindex="-1"></a>---</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Rossouw van Jaarsveld</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org">
<p>Built with Quarto</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>